### ISSUE TITLE
Unable to export annation results

### ISSUE THREAD

**Issue by gmcather** [heartexlabs/label-studio#1019]
Noticed that my data can't be exported correctly even though I tried with all types of output format, it keep throwing error messages like "internal runtime errors", here's the debug information you may be interested in.

![label studio issues](https://user-images.githubusercontent.com/2755198/120726362-c2f16e80-c48c-11eb-9615-52a9ea9c8325.png)

**Comment by makseq** [comment]
@gmcather please, could you show your tasks with annotations as examples (screenshots or task codes - press the </> button on the end of a task row in the data manager). Looks like you have some special characters inside.

**Comment by gmcather** [comment]
I don't really know which line of my data caused this error, any suggestions for that?

**Comment by SAdnen** [comment]
@gmcather since this [pull](https://github.com/heartexlabs/label-studio/pull/723) utf8 has been the default encoding, so probably you are using an old version. To check this, look at the file "d:/users/huiliu/anaconda3/envs/label_studio\lib\site-packages\label_studio\data_export\models.py", line 50, you should find this `with open(filename_results, 'w', encoding='utf-8') as f:`, if you can't see `encoding='utf-8'` then you can add it or even better, download the recent version.

**Comment by gmcather** [comment]
That works after adding encoding utf-8, thanks.
