### ISSUE TITLE
Labels after a linebreak are not displayed (NER tagging)

### ISSUE THREAD

**Issue by uklft** [heartexlabs/label-studio#1208]
When creating Labels on a word after a linebreak, the annotation is not visible. However it shows up in the list of labels to the right.

1. Create new Project
2. Choose labeling Interface NLP > NER default template
3. Open Task with multiple paragraphs
4. Create label on word after newline (\n)
5. Do not see the Label

![Screenshot from 2021-07-23 10-55-52](https://user-images.githubusercontent.com/35134759/126759796-f4b584c6-7fe7-407f-8380-54075f7c09cd.png)

Edit:
In the js log i get:

![Screenshot from 2021-07-23 11-40-05](https://user-images.githubusercontent.com/35134759/126764516-2a3b0d60-c4c3-411e-a052-37d4499c7de6.png)

**Comment by stantonius** [comment]
I am also experiencing the same issue with the same setup. I had concluded this issue was appearing after newlines as well. However I get a different js error:

`DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 1.` 

I do get the same warning message as OP:

`No range found to highlight`

Note that this behaviour is random. 9/10 times, terms in the subsequent paragraphs are not highlighted. However sometimes, especially if a term is just 1 word long, it may randomly decide to highlight.

Hopefully this helps for additional context. I assume this is the same issue but can raise another ticket if not.

Many thanks

**Comment by sharkzeeh** [comment]
Additionally, if one toggles "Select text by words" in the "labeling interface" menu and highlights the word after '\n' (and corresponding sentence) the selection by words does not work.

![image](https://user-images.githubusercontent.com/36710035/126990324-7b251115-9a0b-48df-a60a-3a681222e509.png)

**Comment by jimsandwick99** [comment]
Seems to be the same for me but in case this error helps any more.. seems to repeat (I presume for every instance of a label that is not displayed visually).

<img width="520" alt="Screenshot 2021-07-29 at 10 29 39" src="https://user-images.githubusercontent.com/4035754/127468281-acda83cf-4654-4a2e-86fb-6e31cf34b900.png">

Crhome Version 91.0.4472.164 (Official Build) (x86_64) / MacOS MoJave Version 10.14.6 (18G87)

**Comment by makseq** [comment]
@uklft @stantonius @sharkzeeh @jimsandwick99 Could you please check the latest master commit from the main LS repo? We fixed a lot of problems with NER labeling there.

**Comment by jimsandwick99** [comment]
> @uklft @stantonius @sharkzeeh @jimsandwick99 Could you please check the latest master commit from the main LS repo? We fixed a lot of problems with NER labeling there.

Hi. Thanks for the update. I will try to test it and will feedback in due course. Cheers

**Comment by makseq** [comment]
Now it's in https://github.com/heartexlabs/label-studio/releases/tag/v1.1.1, just do 
pip install -U label-studio
