### ISSUE TITLE
Images are not displayed when importing local tasks from JSON files

### ISSUE THREAD

**Issue by dsmanl** [heartexlabs/label-studio#2086]
**Describe the bug**

I am trying to import tasks from local storage using the label studio Docker image for image annotation. For this purpose I am following the steps described in the documentation - described [here](https://labelstud.io/guide/tasks.html#Import-data-from-a-local-directory) and [here](https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-and-use-local-storage).

While I am able to import tasks from JSON files the references images do not show up in the UI.

**To Reproduce**
1. Create local project structure - e.g.:
```bash
mkdir my_annotation_project
cd my_annotation_project
mkdir myfiles
mkdir myfiles/dataset1
mkdir mydata
```
2. Copy an image and a task definition to `myfiles/dataset1`. The task definition is given by the JSON file:
```json
{
    "data": {
        "image": "/data/local-files/?d=dataset1/1005.jpg"
    }
}
```
3. From the project root run the following Docker command using the latest label studio Docker image:
```bash
docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true --env LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files --env LABEL_STUDIO_USERNAME="user1@user1.de" --env LABEL_STUDIO_PASSWORD="ipwd1234" -v `pwd`/myfiles:/label-studio/files heartexlabs/label-studio:latest label-studio
```
4. In the label studio UI, create a new project and select the `Object Detection with Bounding Boxes` template for the `Labeling Setup`. 
5. In the project's settings go to `Cloud Storage` and configure the local file storage:
* Storage Type: Local files
* Storage Title: mylocalstorage
* Absolute local path: /label-studio/files/dataset1
* File Filter Regex: .*json
* Check `Treat every bucket object as a source file`
* Click `Check Connection` and `Save`
* Synchronise local storage by clicking `Sync Storage` on the recently created local storage
6. In the project's task list you should now see a task being imported, without showing the data/ image referenced in the task's JSON file.

**Expected behavior**

The image referenced in the task definition should be displayed in the UI/ label interface.

**Screenshots**

The following screenshot shows the result after following the steps described above:
![image](https://user-images.githubusercontent.com/67360039/156539298-59756040-7eb7-470e-b178-c12effb98717.png)

Clicking on `task source` indicates that there might be a bug in the task import as you can see that the image reference has been replaced by the task reference:
![image](https://user-images.githubusercontent.com/67360039/156539776-d40e3e07-2354-44cb-a991-4f7453514663.png)

The issue can be solved by updating the task via the API:
![image](https://user-images.githubusercontent.com/67360039/156540068-f879de80-164a-444a-b231-b3e82c02d452.png)

Now the task is showing the referenced image (after hitting refresh)
![image](https://user-images.githubusercontent.com/67360039/156540231-1ffa9f0c-642d-4528-8845-89c0a573d171.png)

as well as the correct task source as specified in the task's JSON definition
![image](https://user-images.githubusercontent.com/67360039/156540434-fd9e9f2c-53bc-4e01-818b-a0bb8a4eef86.png)

**Environment (please complete the following information):**
 - OS: macOS Monterey
 - Docker 4.3.2 (72729)
 - Label Studio Version 1.4.1post1

Thanks a lot for your support!

**Comment by greyeagle** [comment]
I can add that the issue seems the same on Ubuntu and with remote S3 storage. In my case I synced image labeling tasks to `Target Cloud Storage`. I then tried using the same bucket as source on another machine. On syncing the tasks on the new machine, I also get falsely interpreted data, I assume same issue as above.

**Comment by makseq** [comment]
If you check Treat every bucket object as a source file, you have to use "File Filter Regex: .*jpg"

**Comment by greyeagle** [comment]
@makseq : Thank you for that hint. Is this also true if the source folder contains nothing but `.jpg` files? I thought I only need to filter if there are mixed files. What I have is a source folder with JSON for the tasks (this folder is the output of the other machine) and another source folder with the corresponding images (only here I use `Treat every bucket object as a source file`). Both folders contain only one type of file each.

**Comment by dsmanl** [comment]
Thanks for coming back to us, @makseq ! The goal is to import pre-annotated tasks (in Label Studio JSON format) and this is why I have used "File Filter Regex: .*json". Each task is in a single JSON file. In the past it worked quite well using this approach.

If I use .*jpg, the image is displayed correctly. However, pre-annotations are not considered.

![image](https://user-images.githubusercontent.com/67360039/158334276-42c2098c-9dbf-493f-9d41-78754182456a.png)

Thanks!

**Comment by makseq** [comment]
@greyeagle @dsmanl Have you added Local Storage with the same settings to the new project?

**Comment by dsmanl** [comment]
@makseq sorry the delayed reply. Yes, I did. Nothing changed but the Docker image. Unfortunately, I don't have a note on the digest available. Could be about nine months ago.

**Comment by MrNightSky** [comment]
Hi
@[dsmanl](https://github.com/dsmanl) I fullly understand your problem, I spend over 2 days to find how it works. Now I have my own instruction for this case without add task via API.
1. You have to do everything that you have done at the fist message up to stage `5. In the project's settings go to Cloud Storage and configure the local file storage:` At this stage you have to pass **File Filter Regex**, rest it empty or add extension of your files (not task *json) .*jpeg or something else.
2. Also you have not use the button `Treat every bucket object as a source file` **switch it off**
![image](https://user-images.githubusercontent.com/39031563/160407795-bf2b381e-fb59-4f22-a0b6-f067cbe7bde9.png)
3. After all you have no use synchronization! **Don't touch button** `Sync Storage`
4. When you finish with local storage (without synchronization!) just upload your task (json file) via interface (button `import` at the project page). I sure you know where it is:)
![image](https://user-images.githubusercontent.com/39031563/160408792-7a85697f-0542-450d-8f3b-484b4466b7b8.png)

If your json file is correct and your template use correct data name from json task, everything will be downloaded correctly!

I also want to show the example of my .json task for multi-image classification, that was shown [here](https://labelstud.io/playground/#) because I can not find it before.
![image](https://user-images.githubusercontent.com/39031563/160409771-e5eb967c-27b8-4d66-97a2-87fccab22306.png)
As you can see it contain list of dict. Each my path start with `/data/local-files/?d=results/katna_5/`, because I use `/label-studio/files/results` as _Absolute local path_ inside source storage.

I hope it help you

**Comment by makseq** [comment]
@MrNightSky Thank you very much for this instruction, do you mind if we add it to our docs?

**Comment by MrNightSky** [comment]
It will be great!!!

And I want to say, that I'm very impressed by this instrument! I'm sure, that if you solve misunderstandings like that it will be greater!

P.S. If you need better screenshots, or more detail instruction for your documentation, message me.

**Comment by makseq** [comment]
@MrNightSky Could you write this instruction in the .md file? 

https://github.com/heartexlabs/label-studio/blob/master/docs/source/guide/storage.md
it will be compiled to this =>
https://labelstud.io/guide/storage.html#Local-storage

You can create a PR and become a contributor ;-)

**Comment by skinkie** [comment]
I have a different perspective on this take, since I had the same issues as the above. When I wanted to migrate a labeling session between system 1 (sqlite) and system 2 (postgresql).

As a user I would expect that when I get a common JSON export with filenames in it, that it would be sufficient that I:
 1. either copy these files manually over
 2. import the files via the import button

I notice that when I copy the files manually the database does not have the data_import_fileupload entries, and then starts to complain, including code errors. If the user does manage to import these files, the data in tasks will contain the project id being part of the "json" in the data field of tasks. This is very suboptimal. I resolved this with some PostgreSQL tricks.

When option two is taken, all uploaded files will get a new prefix, and being treated as new entries. Again, this is not what I expect.

**Comment by makseq** [comment]
You can modify this code a little:
https://github.com/heartexlabs/label-studio/blob/master/label_studio/data_import/api.py#L449

=> to something like this: 

```
 def get(self, *args, **kwargs):
        request = self.request
        filename = kwargs['filename']
        file = settings.UPLOAD_DIR + ('/' if not settings.UPLOAD_DIR.endswith('/') else '') + filename
        logger.debug(f'Fetch uploaded file by user {request.user} => {file}')

        content_type, encoding = mimetypes.guess_type(str(file))
        content_type = content_type or 'application/octet-stream'
        return RangedFileResponse(request, open(file, mode='rb'), content_type=content_type)
```

**Comment by JonasZaoui2** [comment]
Hello !
Please, I need help on importing pre-annotated data from cloud storage.
I have a bucket s3 where my images are stored. I can sync the source storage on labelstudio and can see all my images.
The issue is coming when I want to import the associated annotations to each image. I have generated a JSON file, but I do not know where to put it in the bucket, what the field “data”: {“image”: ...} should contain, ...
I would really appreciate some help.
Thanks a lot in advance

**Comment by makseq** [comment]
Hello, you should generate many json files - in each of them you have to write JSON dict with data and pre-annotation, like:

```
{
 "data": {"image": "s3://xxx/1.jpg"},
 "predictions": [ { "result": [{"id": "region1", ...}, {"id": "region2", ...}] }
}
```

so, you will have this json as s3://xxx/1.json.

**Comment by leanderme** [comment]
Hi @makseq ,

it is still not clear to me how pre-annotated data can be read in via cloud storage. 

Suppose that in the source folder, there are JPEGs and the respective JSON files with the pre-annotations in the format described above: 
- IMAGE1.jpeg
- IMAGE1.json

So, for each image, there is JSON dict with the data.image key referencing the cloud storage object url, e.g. "s3://xxx/1.jpg" and also stores the predictions.

How should the data be read? I have tried the follwing:
- Creating two source storage connectors with *.JPEG and *.json as file filters. For the media consuming storage connector, I have enabled "Treat every bucket object as a source file" and for the Pre-Annotated Data connector I have switched this option off
- Created one source storage with .*(JPEG|json) with "Enable Treat every bucket object as a source file" enabled

In none of these cases, pre-annotated data was fetched for the respective image files. When only the pre-annotated data connector was synced with "Enable Treat every bucket object as a source file" switched off, the URLs were (of course) not presigned and thus fetching data failed. When the option was turned on, LS generated a presigned url for the JSON file (instead of the respective image file). 

I am sure this is trivial as this is the most basic workflow I can imagine most people are using, but I would be very thankful for a short description on how this should be done. 

Any help is greatly appreciated!

**Comment by makseq** [comment]
You need only one storage. 
1. Prepare your json file - you should pre-calculate image paths beforehand, so your json should look similar to this:
```
{
 "image": "s3://my-bucket/xxx/image1.jpg"
}
```
2. Place your image and json files into the same bucket.
3. Add cloud storage in LS, uncheck "Enable Treat every bucket object as a source file"
4. Enable "Use pre-signed URLs" toggle in the cloud storage
5. Sync your storage (click "Sync" button)

Task data with "image" field should be resolved automatically. 
Hope this schema clarifies the flow a little:
![image](https://user-images.githubusercontent.com/501780/220491188-09c47501-b8b0-4c70-b693-d7309f78f535.png)

**Comment by leanderme** [comment]
Thank you @makseq for the detailed and fast response!

To be clear, in order to have pre-annotated data for each image, there is a bucket with the following structure:
```
└── Data-Bucket/
    ├── image1.jpg
    ├── 1.json
    ├── image2.jpg
    ├── 2.json
    ├── image3.jpg
    └── 3.json
```

the JSON files are formatted according to the LS Common Format, that is: 

```
{
 "data": {"image": "s3://xxx/image1.jpg"},
 "predictions": [ { "result": [{"id": "region1", ...}, {"id": "region2", ...}] }
}
```

So, within the JSON files, there is a reference to the s3 internal location of the respective file. These file locations will be replaced by LS with pre-signed URLs (so that LS Frontend can consume and access them)

Now, when I proceed and:
1. Prepare the json files containing the pre-annotated data
2. Place the image and json files in the same bucket
3. Add cloud storage in LS, and **uncheck** "Enable Treat every bucket object as a source file"
4. Enable "Use pre-signed URLs" toggle in the cloud storage
5. Use a regex filter for json files (since we have unchecked the option "Enable Treat every bucket object as a source file", otherwise LS would try to read the image files as JSON and output an error)
6. And then finally sync your storage (click "Sync" button)

it does not convert the internal file path to pre-signed URLs, but instead outputs:
```
{
  "id": 1,
  "data": {
    "data": {
      "image": "s3://xxx/image1.jpg"
    },
    "predictions": [ { "result": [{"id": "region1", ...}, {"id": "region2", ...} ]
  },
  "annotations": [],
  "predictions": [] // empty
}
```

Sorry for asking again, but I have tried different ways to get this to work for hours without success.

**Comment by makseq** [comment]
@leanderme Thank you for this clear steps. Everything looks correctly in your actions, but all your json is placed into task.data. However, it should have placed 
```
data => task.data, 
predictions => task.predictions
```
but I see 
```
data => task.data.data, 
predictions => task.data.predictions. 
```
It's weird.. 

What LS version do you use?

**Comment by leanderme** [comment]
Apologies @makseq, I should have checked that before: I was using LS v1.0.0, all data is fetched corretly when using the latest version (1.7.1). Thank you for the help!

**Comment by FeriBolour** [comment]
Hello Everyone,
Thanks for all the valuable comments,

I've been trying to follow the same steps on my Windows 10 computer but I don't know if I am doing something wrong or I am missing something. (label-studio version = 1.7.1)

I also set up the Project folder structure as follows:
```
C:\\Users\\farsh\\Downloads\\
└── label_studio_test\\
    └── myfiles\\
        ├── dataset1\\
        │   ├── img1.JPG
        │   ├── img2.jpeg
        │   ├── img3.JPG
        │   └── etc
        └── labels.json
```
before starting _label_studio_ from the command line, I run the following commands: 
```
set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=C:\\Users\\farsh\\Downloads\\label_studio_test
```
This is what my label.json looks like
```
[
  {
    "data": {
      "image": "/data/local-files/?d=myfiles\\dataset1\\img1.JPG"
    },
    "annotations": [
      {
        "result": [
          {
            "id": "4d5fd4182e",
            "type": "rectanglelabels",
            "value": {
              "x": 41.876675,
              "y": 74.05143333333334,
              "width": 7.566500000000001,
              "height": 4.525916666666667,
              "rotation": 0,
              "rectanglelabels": [
                "Node_Flower"
              ]
            },
            "to_name": "image",
            "from_name": "label",
            "image_rotation": 0,
            "original_width": 4000,
            "original_height": 6000
          },
          {
            "id": "acb4887401",
            "type": "rectanglelabels",
            "value": {
              "x": 43.368900000000004,
              "y": 62.697983333333326,
              "width": 7.850225000000001,
              "height": 5.436633333333333,
              "rotation": 0,
              "rectanglelabels": [
                "Node_Flower"
              ]
            },
            "to_name": "image",
            "from_name": "label",
            "image_rotation": 0,
            "original_width": 4000,
            "original_height": 6000
          }
        ],
        "ground_truth": false
      }
    ]
  },
  {
    "data": {
      "image": "/data/local-files/?d=myfiles\\dataset1\\img2.jpeg"
    },
    .
    .
    .
```

Then in label-studio UI, after creating a project and setting up the _Object Detection Labeling Config_ I go to _Cloud Storage_ settings and do the following:
![image](https://user-images.githubusercontent.com/57817579/226133758-6ec09838-8d73-4e02-b816-65734dae1f43.png)

and this is what it looks like
![image](https://user-images.githubusercontent.com/57817579/226133772-02852a88-cfb1-4bdb-bff2-b96770daae8f.png)

And I do not click **_Sync Storage_**.

And then import the _labels.json_ file.

But I still cannot see the images:
![image](https://user-images.githubusercontent.com/57817579/226133914-c6a3a06f-5fdc-4e8d-b9f4-528d66ffce54.png)


I'd really appreciate it if anyone could help me with this.

**Comment by makseq** [comment]
@FeriBolour I see a few suspicious things here: 
1. try to use / instead of \\ in labels.json for image paths
2. if (1) doesn't help, try to use /  instead of \\ in local storage settings in absolute path
3. check lowercase and uppercase in image filenames

To facilitate testing you can open your links directly in the browser address line and try typing filename there.

**Comment by FeriBolour** [comment]
@makseq  Thank you for the quick reply.

> 1. try to use / instead of \ in labels.json for image paths

I thought maybe in windows it should be \\ .
But I did as you said.
Here's what a filename looks like now:
```
[
  {
    "data": {
      "image": "/data/local-files/?d=myfiles/dataset1/A4_2023_03_04.JPG"
    },
    "annotations": [
      {
        "result": [
          {
            "id": "4d5fd4182e",
            "type": "r
            .
            .
            .
```
And this is what the source code for an image looks like after importing the labels.json file:
![image](https://user-images.githubusercontent.com/57817579/226152079-965a0258-2a18-4f6c-a7cc-dc19fd083209.png)

The images still don't display.
> 2. if (1) doesn't help, try to use /  instead of \ in local storage settings in absolute path

I did this as well.
here's what it looks like now:
![image](https://user-images.githubusercontent.com/57817579/226152096-7b7b98a1-508a-488c-bd6b-23920c509251.png)

I also tried fixing the path in the command line but entering:
`set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=C:/Users/farsh/Downloads/label_studio_test`

Still no display.

> 3. check lowercase and uppercase in image filenames

All the json files were generated automatically. I used the _label-studio-converter_ to generate the file. I am quite confident the names are correct but I'll check again.

> To facilitate testing you can open your links directly in the browser address line and try typing filename there.

I entered the following in the address bar directly and it doesn't show anything:

`http://localhost:8080/data/local-files/?d=myfiles/dataset1/A4_2023_03_04.JPG`

`http://localhost:8080/data/local-files/?d=dataset1/A4_2023_03_04.JPG`

**Comment by makseq** [comment]
What exact error does browser write?

**Comment by FeriBolour** [comment]
@makseq 
![image](https://user-images.githubusercontent.com/57817579/226153096-1a188227-27e2-4e0a-9046-dce12cc3e75a.png)

Again, thank you for the quick responses and for helping out.

**Comment by makseq** [comment]
I mean when you open a direct link in new tab

**Comment by FeriBolour** [comment]
@makseq 
Oh sorry.

![image](https://user-images.githubusercontent.com/57817579/226153236-fac71306-6e7e-40a8-af91-aaf36233dfee.png)

**Comment by makseq** [comment]
![image](https://user-images.githubusercontent.com/501780/226153347-54de2917-b45c-4b66-88ea-cc95af64ef22.png)
why `\\` is used here? try `\` or even `/` instead.

**Comment by FeriBolour** [comment]
I did change that as you suggested.
I put a picture of it in my previous reply.

This is what it looks like now:
![image](https://user-images.githubusercontent.com/57817579/226153425-d0b456be-70f7-43f6-a172-6315e69c599c.png)

**Comment by makseq** [comment]
Have you tried both `/` and `\`? Doesn't help?

**Comment by FeriBolour** [comment]
@makseq Yes, I have. It doesn't make a difference.

For more context,
Here is some other information that you might find useful (I am going to share pics for both when using `\` and `/`.

This is what I see when actually syncing the cloud storage while checking the option "Treat every bucket object as a source file".

using `/` :
![image](https://user-images.githubusercontent.com/57817579/226181939-3d0c3fef-9ec5-400b-92ca-cb2dccee4110.png)
![image](https://user-images.githubusercontent.com/57817579/226181960-c062f5cb-e96b-4ec4-8160-db8c11cc7904.png)
I find it weird that the id starts with 4462. And this number is not random. I have 234 images in my bucket. Every time I sync the cloud storage it starts with the previous id number plus 234. For example, the next time I sync the storage, it will start with 4696.

And here are the same results when using `\` :
![image](https://user-images.githubusercontent.com/57817579/226182316-e7f1c55f-d708-46e9-9a3d-d99283aa77d5.png)

![image](https://user-images.githubusercontent.com/57817579/226182332-067fdebb-0211-4e08-99d3-a5af372e49ee.png)

As you can see, this time it starts with the id 4696 since I sync it again.

I don't know if this information is helpful. But I wanted to share it for context.

Thank You for helping out.

**Comment by makseq** [comment]
@FeriBolour didn't you find the solution? Sorry, I have no ideas what is wrong there..

**Comment by maddison-rose** [comment]
Hi All, 

I have experienced similar issues recently.

I am starting the application with the following parameters:

```
set LABEL_STUDIO_BASE_DATA_DIR=C:/Data/label-studio
set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=C:/Data/Media
label-studio start
```

I then log in and set the absolute local path to the following:
![image](https://user-images.githubusercontent.com/105178068/231901074-48d123a6-4182-41f3-8ab3-224ea259a5a5.png)

and sync my folder, the corresponding JSON is structured as follows:
```
{
    "document": [
        {
            "page": "/data/local-files/?d=Melanoma%5CImmage%5CA%201207%201_001.jpg"
        },
        {
            "page": "/data/local-files/?d=Melanoma%5CImmage%5CA%201207%201_002.jpg"
        },
        {
            "page": "/data/local-files/?d=Melanoma%5CImmage%5CA%201207%201_003.jpg"
        }
    ]
}
```

This is where things get interesting, when I do this the first time i.e. delete the db directory and start from scratch.
It server the files from the local source just fine, however if I log in and out a few times and restart the application. it at some point stops serving the files and I receive the following messages. from the console and application respectivly
![image](https://user-images.githubusercontent.com/105178068/231901898-a653cf87-5c39-428f-8006-e996004c7cff.png)
![image](https://user-images.githubusercontent.com/105178068/231902462-afd2a5e5-3f94-49bc-9112-678198a0113a.png)

 Further digging in the developer console shows that the cookie header does not have a secure directive and is set to httponly.
![image](https://user-images.githubusercontent.com/105178068/231902253-9915f743-1c15-47b6-add7-93d8f605b8fc.png)

does anyone know what might be causing this behavior, and how I might stop this?

**Comment by makseq** [comment]
@maddison-rose 

1 Check this url http://localhost:8080/data/local-files/ (8080 is your LS port)
![image](https://user-images.githubusercontent.com/501780/231906389-1fb89356-b4f5-4470-8f9a-528240f846a0.png)
it should return 403 error. I see in your logs 404, it seems your Local Storage is not enabled. 

2 Create superuser 
```
label-studio init --username superuser@test.ru --password 123456
```

run LS this way
```
set LABEL_STUDIO_BASE_DATA_DIR=C:\\Data\\label-studio
set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=1
set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=C:\\Data\\Media
label-studio start
```

check `/version` page. There should be actual values of these 2 vars:
`LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED` and `LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT`
are they match you typed at the start up? 

3 Probably the issue is in `/`. In (2) I replaced it to `\\`, maybe it solves this problem. Please let me know!

**Comment by FeriBolour** [comment]
> @FeriBolour didn't you find the solution? Sorry, I have no ideas what is wrong there..

No I did not.
I just switched to using another Annotation Tool.

It's a shame because I really enjoyed using label-studio. And I don't understand why it is so difficult to upload already annotated data. It seems like it is easier to deploy a whole ML model in the tool than just uploading its predictions.

But again, thanks for trying to help out. I'll be looking at this thread every once in a while to see if there's a solution.

**Comment by leonardoandresgaray** [comment]
Hey!

There is a workaround, jsut upload the file first, and the look for the task itsefl

project.import_tasks(os.path.join('C:\Users\.....\images\1280', 'IMG_20230422_105651.jpg'))

**Comment by williamAddison** [comment]
@makseq I am having very similar problems as the people above, I am working with S3 and I can display the right images after following the instructions above but I can't get the annotations to show up visually even though the annotations can be seen and as far as I can see are formatted correctly. Any ideas? Here is a sample of my tasks that I create (and yes I have tried with making these into predictions not annotations):

> {
  "id": 33,
  "data": {
    "image": "http://hercules:30600/master.full.json/0001397-601295486976-1_Detect_EBR.AdlRef_Top.png"
  },
  "annotations": [
    {
      "id": 30,
      "created_username": "",
      "created_ago": "1 minute",
      "result": [
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        },
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        },
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        },
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        }
      ],
      "was_cancelled": false,
      "ground_truth": false,
      "created_at": "2023-06-15T19:47:37.008854Z",
      "updated_at": "2023-06-15T19:47:51.425691Z",
      "lead_time": 1265.961,
      "task": 33,
      "completed_by": null,
      "parent_prediction": null,
      "parent_annotation": null
    }
  ],
  "predictions": []
}

**Comment by CervantezG** [comment]
I was able to fix my issue by setting LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT to the local path directory.  I also put quotes around the env variable.

**Comment by tijmenvanetten** [comment]
> Hello, you should generate many json files - in each of them you have to write JSON dict with data and pre-annotation, like:
> 
> ```
> {
>  "data": {"image": "s3://xxx/1.jpg"},
>  "predictions": [ { "result": [{"id": "region1", ...}, {"id": "region2", ...}] }
> }
> ```
> 
> so, you will have this json as s3://xxx/1.json.
> 
> OR
> 
> you can just connect s3 source storage, but DO NOT sync it. Then import your json with multiple tasks, urls should look like in my example below.

What if I want to link files from an Azure Blob Storage?

**Comment by JoelOscarsson** [comment]
Hello i have been trying to solve this for 2 days now and feel like i am pretty close.
My tree structure is 

└── Images/
    ├── image1.jpg
    ├── image2.jpg
    ├── image3.jpg

└── labels/
    ├── 1.json
    ├── 2.json
    └── 3.json

I haven't "Synced" as suggested

![Screenshot from 2024-02-06 16-39-02](https://github.com/HumanSignal/label-studio/assets/112272227/67f657f3-c400-4ec0-8b5e-bfe4781413e6)


I have trying to solved it like @MrNightSky However my Json file looks a little different. And i cannot really understand why the json doesn't connect to the corresponding .jpg file it's pointing at. Could there be an issue with how the json is written?

 

> {  
> "data": {  
> "image": "/home/joel/cdwww/converter/preannotated/exp2/images/frame_0012A.jpg"  
> },  
> "predictions": [  
> {  
> "result": [  
> {  
> "id": "7c91a7cdfd",  
> "type": "rectanglelabels",  
> "value": {  
> "x": 39.4531,  
> "y": 76.95309999999999,  
> "width": 12.206999999999999,  
> "height": 22.526,  
> "rotation": 0,  
> "rectanglelabels": [  
> "Person"  
> ]  
> },  
> "to_name": "image",  
> "from_name": "label",  
> "image_rotation": 0,  
> "original_width": 1024,  
> "original_height": 768  
> }  
> ]  
> }  
> ],  
> "annotations": []  
> }
> 


I also use these commands in order in terminal before starting up label-studio.

export LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/joel/cdwww/converter/preannotated/exp2 
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true

label-studio


The furthest it gets is like this but i have no images showing
![Screenshot from 2024-02-08 13-59-30](https://github.com/HumanSignal/label-studio/assets/112272227/2f77b892-3396-4521-9753-d8f3206e87a1)

**Comment by codebitsofg** [comment]
Has anyone find a solution to this?

**Comment by makseq** [comment]
@JoelOscarsson 
All images are go through your browser, so all paths should be go through http domain name. In this example of a task I don't see a correct image path: 
```
"data": {
  "image": "/home/joel/cdwww/converter/preannotated/exp2/images/frame_0012A.jpg"
},
```

If you set `LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/joel/cdwww/converter/preannotated/exp2`, it should be something like this: 

```
"data": {
  "image": "/data/local-files/?d=Images/image1.jpg"
}
```

so, it mean that `/home/joel/cdwww/converter/preannotated/exp2/Images/image1.jpg` exists and LS will serve `Images` folder as `http://<your-label-studio-url>/data/local-files/?d=Images/image1.jpg`

**Comment by aurexav** [comment]
Windows users, please check https://github.com/HumanSignal/label-studio/issues/6173!!!

**Comment by pascal-maker** [comment]
Here is my solution
---

## ✅ **Label Studio – Error Loading URL from \$image Value (CORS Fix & Setup Guide)**

**Problem:**
Label Studio shows the error:

> ❌ *"There was an issue loading URL from \$image value"*

Even though the image URL is valid (e.g., `http://10.10.20.164:8081/...`), the images do not display. This is often due to **CORS** (Cross-Origin Resource Sharing) being blocked, especially when using a local Python HTTP server.

---

### ✅ **Solution**

You need a **CORS-enabled HTTP server** to serve your images. Here's how to fix it step by step:

---

### 🔧 1. Serve Your Image Folder with CORS Support

Create a file called `cors_server.py`:

```python
import http.server
import socketserver

class CORSRequestHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        super().end_headers()

PORT = 8081  # or any free port

with socketserver.TCPServer(("", PORT), CORSRequestHandler) as httpd:
    print(f"Serving at http://0.0.0.0:{PORT}")
    httpd.serve_forever()
```

**Start the server from the directory that contains your images:**

```bash
cd T:\Images
python cors_server.py
```

Your images will now be accessible at:

```
htt
...
```

---

### 🏷️ 2. Set Up Label Studio Config

**Use this XML labeling config:**

```xml
<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
  </RectangleLabels>
</View>
```

💡 Make sure the `value="$image"` matches your JSON field.

---

### 🗂️ 3. Import Tasks in Label Studio

Your JSON task file should look like:

```json
{
  "data": {
    "image": "http://10.10.20.164:8081/yourimage.jpeg"
  }
}
```

Then:

* Go to your project
* Click **Import**
* Upload the `.json` file

---

### 🧪 4. Verify and Test

* In **Labeling Interface → Configure data**, ensure “Use image from” is set to `$image`
* Open a task — the image should now load without errors.

---

### ✅ Result

✔ Images load from your local server
✔ Label Studio can now annotate without CORS issues
✔ Works with bounding boxes, classification, etc.

---

**Comment by pascal-maker** [comment]
When running Label Studio with Docker, you might find that certain elements of your site aren't rendering correctly. This is often due to Content Security Policy (CSP) headers. To resolve this, you need to disable the CSP header.

After following your initial server setup steps, use the following Docker command to run Label Studio, ensuring the CSP header is disabled:


docker run -p 8082:8080 -e LABEL_STUDIO_CSP_HEADER_DISABLED=true heartexlabs/label-studio:latest


Always check your browser's developer tools (console and network tabs) to identify any rendering issues or blocked resources.This will provide valuable insights into what might be going wrong with your site and help you troubleshoot effectively.

**Comment by pascal-maker** [comment]
"Ensure that the CORS server is running properly and use its URL in the JSON file for your image URLs."
