### ISSUE TITLE
Make image size full-screen

### ISSUE THREAD

**Issue by maiiabocharova** [heartexlabs/label-studio#2251]
Hello, is there any way to make image full-screen for example [here] (https://drive.google.com/file/d/1UiYy_viqzKvKngFcGn7vlVoH6q7DsYS2/view?usp=sharing) I made a screenshot of the problem

There is so much space wasted, but image is very small and uses only a third part of available space
It would be great to set an image width to be maximum, and be able to scroll down to label lower parts of the images

**Comment by hlomzik** [comment]
Hi! We use `maxHeight` to fit image canvas into browser viewport, but you can disable this by adding `maxHeight="auto"` to `Image` tag.

**Comment by zeljkomarinkovic** [comment]
There is no maxHeight parameter in [docs](https://labelstud.io/tags/image.html#main)! Setting `maxWidth="auto"` still leaves with a lot of unused space 

![image](https://user-images.githubusercontent.com/23746207/169826766-fd7e6741-c869-46af-8d53-fcf3ae971f04.png)

```
<View>
  <Image name="image" value="$image" zoom="true" zoomControl="false" rotateControl="false" maxWidth="auto"/>
  <RectangleLabels name="label" toName="image" strokeWidth="1">  
    <Label value="Car" background="blue"/>
    <Label value="Person" background="#FFA39E"/>
    <Label value="Bicycle" background="#D4380D"/>
    <Label value="Motorcycle" background="#FFC069"/>
    <Label value="Scooter (el sparkesykkel)" background="#AD8B00"/>
    <Label value="Truck" background="#D3F261"/>
    <Label value="Bus" background="#389E0D"/>
    <Label value="Tram" background="#5CDBD3"/>
  </RectangleLabels>
</View>
```

**Comment by hlomzik** [comment]
My answer was for described problem when image is much higher than a screen given its aspect ratio.

In your case the problem is in default zoom and also in detected canvas size (it's calculated as the size for image zoomed in to fit maximum space on screen, which is not good for small images) We'll deal with this things very soon, we already have a plan for canvas/zoom improvements, and [the first step is already made](https://github.com/heartexlabs/label-studio-frontend/commit/75f21ac213dd1e83efa8d0778153b3a8ff6c2cbf)
