### ISSUE TITLE
Brush labelling project won't load on iOS

### ISSUE THREAD

**Issue by madhavajay** [heartexlabs/label-studio#2593]
**Describe the bug**

My segmentation projects in label studio 1.5.0 simply wont load on either Safari or Chrome on iPad or iPhone, it just shows a resizing box loading animation. Is this supported? I would love to do brush segmentation with the iPad pencil.

This is on both iPhone and iPad in Safari and Chrome (as well as Request Desktop Mode)

**To Reproduce**
1. Go to a brush labelling project

**Expected behavior**
It should load.

**Screenshots**
![IMG_46575C7A3852-1](https://user-images.githubusercontent.com/2882739/177016917-23c09142-5055-438d-add1-59fee1c5c1e6.jpeg)

**Environment (please complete the following information):**
 - OS: iOS 15, iPhone and iPad Safari and Chrome
 - Label Studio Version: 1.5.0 docker container

**Additional context**

**Comment by madhavajay** [comment]
This must be a bug in `1.5.0` because `1.4.1` is loading, however I cannot draw with the apple pencil.
This example seems to work though:
https://codesandbox.io/s/qr4uq

**Comment by madhavajay** [comment]
Hi @makseq its still not working. I tried in incognito to make sure the .js isn't cached. In the safari remote debugger I see an error.

<img width="435" alt="Screen Shot 2022-07-04 at 11 24 47 pm" src="https://user-images.githubusercontent.com/2882739/177164009-5f6305ed-fb82-4938-8713-d10d907ea4cf.png">

Unfortunately due to all the minification it's not possible to see the line. Is there a way I can run the container in dev mode without source minification and say hot reloading so I can debug it?

**Comment by makseq** [comment]
@madhavajay please try `pip install label-studio==1.5.0.post0`

**Comment by madhavajay** [comment]
@makseq I guess this can be closed since it loads, but I have a seperate issue relating to being able to use it.

**Comment by Garstig** [comment]
Hi @makseq, 

for me it does not work at all on IPad. I tried to start a segmentation project but I can't use the brush since every touch only scrolls the app. Does not matter if I use my finger or the pencil.

pip freeze output:

label-studio==1.5.0.post0
label-studio-converter==0.0.40
label-studio-tools==0.0.0.dev14
launchdarkly-server-sdk==7.3.0


Should I open a new issue?

**Comment by makseq** [comment]
@Garstig https://github.com/heartexlabs/label-studio/issues/1982#issuecomment-1208746979 --- we have this issue about your problem. Also we are preparing a fix with one of our contributors. If you want, we can ping you when it's ready for tests.

**Comment by madhavajay** [comment]
@Garstig also, you can see my temporary fix here:
https://github.com/heartexlabs/label-studio-frontend/pull/802

Just build that frontend code with `build-bundle` and copy it into the `label-studio` checkout and build the container.

**Comment by Garstig** [comment]
hi @madhavajay, 

I just tried to build your temporary fix, but actually I have no real clue on how to do so since I am very unexperienced with frontend stuff. Could you review the steps I tried and please guide me in what to try next? 

- I cloned https://github.com/heartexlabs/label-studio-frontend and updated your file as you did in your PR. (A quick google research didn't give me a way to clone from a PR). 
- Then I thought I probably need to install npm packages to build it. So I did it with npm install --force (without --force I had dependency issues)
- Then I installed build-bundle with "npm install --save build-bundle" but the package is not found. when I try to use it.

**Comment by haofengsiji** [comment]
> hi @madhavajay,
> 
> I just tried to build your temporary fix, but actually I have no real clue on how to do so since I am very unexperienced with frontend stuff. Could you review the steps I tried and please guide me in what to try next?
> 
> * I cloned https://github.com/heartexlabs/label-studio-frontend and updated your file as you did in your PR. (A quick google research didn't give me a way to clone from a PR).
> * Then I thought I probably need to install npm packages to build it. So I did it with npm install --force (without --force I had dependency issues)
> * Then I installed build-bundle with "npm install --save build-bundle" but the package is not found. when I try to use it.

Can test it on this branch "https://github.com/heartexlabs/label-studio/tree/fb-dev-3132-brush-ipad". It is truly a fantastic feature. But still, need to be improved.
