### ISSUE TITLE
How can i get the original filename instead of url path in text filed ?

### ISSUE THREAD

**Issue by Gladiator566** [heartexlabs/label-studio#2700]
Hello, 
I‘m using LS to do NER task, I prepare my data in `.txt` format which contains plain text with multiple lines,  then I import data into LS using online web UI,  treat them as Time Series format, because I want to annotate these multiple lines of content in one task.
I got `text` field displayed as follow
![image](https://user-images.githubusercontent.com/22348637/179917316-4bd1c539-a1c4-4826-a422-3717151c7e5f.png)
![image](https://user-images.githubusercontent.com/22348637/179919071-d167ea0b-d7eb-4df4-8acf-27773de10353.png)

My question is: Can I get the **original txt filename**(eg. `task1.txt`)  instead of the **url path** to this upload file in text field?

here is my text field config:
```<Text name="text" value="$text" valueType="url" saveTextResult="yes"/>```

Is there anyway to do so ? 

Thank you !

**Comment by makseq** [comment]
Hello, we have a column `Upload filename`, this is almost what you need:
![image](https://user-images.githubusercontent.com/501780/180515688-49af9e50-1085-4158-b7e3-ffb57ec9a654.png)

**Comment by mzhadigerov** [comment]
@makseq  5 thumb downs, "closed as completed". Nice

**Comment by PiotrRyw** [comment]
It is not resolved. "Closed as complete" is inaccurate.

AND if you want to sort by your file-name... not possible. Because it got a seemingly random string attached to the beginning of it, so now you have:
dah1dho9-photo_nr_004.png
ebbfba2h-photo_nr_001.png
fjoo610i2-photo_nr_176.png
ggoh940-photo_nr_002.png
etc.

instead of
photo_nr_001.png
photo_nr_002.png
photo_nr_004.png
photo_nr_176.png

And it's plain weird that the Label Studio maybe gets the full path to the local storage (since it's loading it through the file browser ui?) yet it does not retain it anywhere. I am going to write a python script to go through the generated COCO annotation file and replace the nonsensical path with a proper one using regex but like... why.

There will be a lot of find_and_replace with ""..\\..\\label-studio\\label-studio\\media\\upload\\4\\7f718649-"

**Comment by notsadness** [comment]
@PiotrRyw agreed it's annoying AF. I found this after experiencing the same issue:

`https://github.com/HumanSignal/label-studio/issues/729`
