### ISSUE TITLE
How to track which version is using which frontend version's minified file?

### ISSUE THREAD

**Issue by nabinkhadka** [heartexlabs/label-studio#272]
Is there anyway we can know which version of frontend's minified file is used by a version of this repo?

For example: In label-studio==0.5.0, which commit/tag from label-studio-frontend is used?

**Comment by makseq** [comment]
@nabinkhadka starting from 0.7.0 release of Label Studio Backend we have synced LS backend and frontend versions. They have the same versions now. 
Unfortunately there is no way to know commit by minified js file name.

**Comment by nabinkhadka** [comment]
Ok. Sounds good if they are same from now. Thank you @makseq for your response.

**Comment by nabinkhadka** [comment]
@makseq https://github.com/heartexlabs/label-studio/releases and https://github.com/heartexlabs/label-studio-frontend/releases

I don't see v0.7.0 in both. Did you mean to say after 0.7.0?

**Comment by hlomzik** [comment]
Hi, @nabinkhadka! Frontend package goes on some small distance after main package because of release and check processes. I published 0.7.0 to npm/github packages yesterday, but there is important bugfix arriving, so today I'll publish 0.7.1 and make a corresponding release finally! Sorry for waiting.

**Comment by hlomzik** [comment]
Hi, @nabinkhadka! We finally fixed all the bugs related and released 0.7.1 — https://github.com/heartexlabs/label-studio-frontend/releases
Next time gap will be shorter!
