### ISSUE TITLE
Polygon and Rectangle examples returning errors

### ISSUE THREAD

**Issue by ghandic** [heartexlabs/label-studio#286]
**Describe the bug**
When using `Rectangle` or `Polygon`  examples from https://labelstud.io/tags/rectangle.html and https://labelstud.io/tags/polygon.html respectively inside the config.xml using the autogenerated sample data it crashes on the frontend (spinner of death) and in the browser console there was an error `TypeError: e.selectedValues is not a function`

**To Reproduce**
1. Copy example Tag code from docs
2. Add into config.xml
3. Autogenerate a task
4. Add 1 or more polygons and submit (if using Rectangle just clicking the image breaks the UI and console logs error: `TypeError: "e is null"`

**Environment (please complete the following information):**
 - OS: Backend running in Docker, host machine: MacOS 10.15.4
 - Browser: Firefox 75.0

**Additional context**
I can use PolygonLabels and RectangleLabels as a workaround but would be nicer to use Rectangle and Polygon as I have only one type of object to detect

**Comment by hlomzik** [comment]
Hi, @ghandic! We've just fixed this tags so they work again. The only obvious limitation for now — they can't be used simultaneously because we don't have any toggle to switch between drawing tools (as it works for RectangleLabels and others, because labels itself are such a toggles).

Playground is still broken, but we'll update labelstud.io soon. You can already use this tags in your project with new 0.7.1 version. Thanks for reporting!

**Comment by makseq** [comment]
Solved in playground too.
