### ISSUE TITLE
Does This tool collect User uploaded Data?

### ISSUE THREAD

**Issue by purnasai-cyient** [heartexlabs/label-studio#2902]
Hi, 

I have installed this tool using the "pip" command from your home page. We have tried the tool with sample data. We have a question of doubt. Does this tool collect data that the user uploaded to this tool(online/local)? 

Please let us know. Thank you
@makseq @niklub

**Comment by makseq** [comment]
Hi, please check this docs: https://labelstud.io/guide/#Information-collected-by-Label-Studio
LS doesn't collect any user uploaded data. Additionally, you can configure LS so that only the annotator's browser has access to your data. LS tries to avoid any data reading by security reasons (if you don't import images/media explicitly inside).
