### ISSUE TITLE
Files with Korean characters in the name are not exported

### ISSUE THREAD

**Issue by rachelbae218** [heartexlabs/label-studio#3177]
**Describe the bug**
When exporting bounding box annotations with with Korean Characters in the source image name, 
only the annotation is exported (with scrambled character names) and the image files are not. 

**To Reproduce**
1. Import image with korean characters in the name 
2. annotate
3. export in any format
4. annotations are successfully exported ( with scrambled characters) but images are not

**Expected behavior**
All annotations AND images are exported successfully 

**Screen shots**
![스크린샷 2022-11-01 오전 7 26 15](https://user-images.githubusercontent.com/102227366/199121840-919be76b-96dd-4db9-a6c5-1d88cd7ee477.jpg)
![스크린샷 2022-11-01 오전 7 27 02](https://user-images.githubusercontent.com/102227366/199121841-a95a2fdb-0654-477e-82cf-2263855641c1.jpg)

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Label Studio Version 1.6.0

**Comment by makseq** [comment]
Are you sure it's related to file names? 
Usually LS tries to avoid touching users input data directly, so it just shouldn't export any images. Therefore it might be super long (because of image/other resources downloading to the backend), and it's another reason to avoid exporting with images. 
The simple solution is to manually copy images to the export folder.
