### ISSUE TITLE
Exporting to YOLO do not include all the images

### ISSUE THREAD

**Issue by TByte007** [heartexlabs/label-studio#3212]
When I try to export in YOLO format an imported dataset with some added new images the resulting ZIP contains ONLY the added images and not the original dataset images while containing the txt for both. It makes no sense. Now I have to unpack the ZIP add the images repack it again. I'm I missing something because it is pretty much useless that way ?
Best regards!

 - OS: FreeBSD 13.1
 - Label Studio Version 1.6

**Comment by makseq** [comment]
LS backend avoids touching user data, because of 
1. security policy
2. time for image downloading might be huge and lead to timeouts even for 10-50 images

You can try to run LS this way:
```
CONVERTER_DOWNLOAD_RESOURCES=1 label-studio
```

But don't know how long we will support this.

**Comment by TByte007** [comment]
> LS backend avoids touching user data, because of
> 
>     1. security policy
> 
>     2. time for image downloading might be huge and lead to timeouts even for 10-50 images
> 
That doesn't make sense. Why would it take a long time or timeouts ? Web servers / clients support downloading multi gigabytes files for many years. And what if ALL the files were uploaded ? I don't understand. It literally makes no sense to me.
> 
> You can try to run LS this way:
> 
> ```
> CONVERTER_DOWNLOAD_RESOURCES=1 label-studio
> ```
> 
> But don't know how long we will support this.

But without that the whole export makes no sense. It's exporting an almost empty file and you have to go find the files by hand. What's the point of that ?

**Comment by makseq** [comment]
LS server is a bad way to host and upload files, because it uses the same workers for image hosting as django app. And we never design LS as a hosting solution for media. Image uploads via GUI are only for toy labeling, serious labeling tasks use Cloud Storages (s3/gcs) usually. 

So, there is a dilemma: LS backend should access storages directly. When you are working alone or in a tiny company - it's ok. When you use LS as an enterprise - enterprise users are much patience if they know that LS backend never touches their data. Our cloud solution uses the same codebase, so it's critical to follow this rule. 

> Web servers / clients support downloading multi gigabytes files for many years.

If LS starts putting 1k images to zip archive, it will take much more time to archive it. This means you will get timeout, because maximum time to wait for django workers ~300 second, and you will never get the export file. Now imagine how export time increases If images are stored in a storage ;-)

**Comment by TByte007** [comment]
> LS server is a bad way to host and upload files, because it uses the same workers for image hosting as django app. And we never design LS as a hosting solution for media. Image uploads via GUI are suitable only for toy labeling, serious labeling tasks use Cloud Storages (s3/gcs) usually.
> 
**Now I got your idea. Thank you for the explanation!**
Although the server's local storage is a "cloud storage" too. And the "local storage" could not be really local but mounted from actual hardware/remote storage. And let's say some companies dont want to store particular data sets on public (overpriced?) services when they own multi terabyte storage solutions fast and at "home".

> So, there is a dilemma: LS backend should access storages directly. When you are working alone or in a tiny company - it's ok. When you use LS as an enterprise - enterprise users have more peace of mind knowing that the LS backend never touches their data. Our cloud solution uses the same codebase, so it's critical to follow this rule.
> 
> > Web servers / clients support downloading multi gigabytes files for many years.
> 
> If LS starts putting 1k images to zip archive, it will take much more time to archive it. This means you will get timeout, because maximum time to wait for django workers ~300 second, and you will never get the export file. Now imagine how export time increases If images are stored in a storage ;-)
> 

Well, I host my own web services which have to "zip" multi-gig files. It's doable and they do not timeout - everything has settings. But now understanding the whole idea and that doesn't matter really. Although the exports (and imports) should be somewhat more user friendly. I'm sorry that I have to say it like that but the current import is a ... well a mess. Took me hours to understand why and what is going on (although big part of the problem was that bug with the "labels" :D )

> Anyway, does this help?
> 
> ```
> CONVERTER_DOWNLOAD_RESOURCES=1 label-studio
> ```

I want to do it the right way especially if that will not be supported. 
**Thank you again from the explanations!**

**Comment by makseq** [comment]
Thank you for your questions! 
Please let me know if `CONVERTER_DOWNLOAD_RESOURCES=1 label-studio` is working.

**Comment by okiane** [comment]
> Thank you for your questions! Please let me know if `CONVERTER_DOWNLOAD_RESOURCES=1 label-studio` is working.

Hi, I am facing similar issue. I would like to export my annotations along with my images (not uploaded to LabelStudio interface but stored in a parent local directory) in YOLO format. 

I tried using `CONVERTER_DOWNLOAD_RESOURCES=1 label-studio` or `LOCAL_FILES_SERVING_ENABLED=true CONVERTER_DOWNLOAD_RESOURCES=1 label-studio`, the exported YOLO image folder still comes out completely empty. 

This is a huge problem because I cannot match the annotation to the image. This is because

- The exported annotated .txt file is named as e.g., 00001.txt, ... and I do not know how these IDs are generated. It has no reference to the original image filename or ID in the LabelStudio database. 
- Furthermore, some images are not annotated (because there are no objects / bounding box). Hence, I cannot simply match the running ID to the image.
- Lastly, this is made worst as my images are stored in different subfolders:
  ```
  project
  .
  +-- parent_folder
  +-- folder_1
  |   +-- image_01.jpg
  |   +-- image_02.jpg
  +-- folder_A
  |   +-- image_01.jpg
  |   +-- image_02.jpg
  ```

Is there another way to do this? I am using Community version 1.6.0 on a Linux computer. Looking forward to your advice.

**Comment by KonstantinKorotaev** [comment]
Hi @okiane 
Could you please share your task source?
You can find it in the Data Manager

**Comment by Timouri** [comment]
I found a way to resolve the issue. The steps that helped were:
1. Open the drawer menu.
2. Go to the "Organization" section (http://localhost:8080/organization?page=1).
3. Click "API Token settings".
4. Enable "Legacy Tokens (Enable legacy access tokens, these do not expire)".
After that I logged back into the project (http://localhost:8080/projects/<PROJECT_ID>/data) and clicked "Export", selecting the "YOLOv8 OBB with Images" format. 

The ZIP file I received contained all the needed images.

I’m not sure why this fixed the problem, but it did.

**Comment by aboev** [comment]
> I found a way to resolve the issue. The steps that helped were:
> 
> 1. Open the drawer menu.
> 2. Go to the "Organization" section (http://localhost:8080/organization?page=1).
> 3. Click "API Token settings".
> 4. Enable "Legacy Tokens (Enable legacy access tokens, these do not expire)".
>    After that I logged back into the project (http://localhost:8080/projects/<PROJECT_ID>/data) and clicked "Export", selecting the "YOLOv8 OBB with Images" format.
> 
> The ZIP file I received contained all the needed images.
> 
> I’m not sure why this fixed the problem, but it did.

Thanks, it works! I strongly advice **label-studio** team to hire you!
