### ISSUE TITLE
Export polygons to YOLO

### ISSUE THREAD

**Issue by adlero4ek** [heartexlabs/label-studio#3562]
Hi. I use Label Studio as http://localhost:8080/ and want to export to YOLO format but «YOLO» blocked in the list of exporting options. How to fix it?[
![Безымянный](https://user-images.githubusercontent.com/122682949/212476900-e562f4ae-23dc-4afe-8fe9-1e4823d19bf0.png)
](url)

**Comment by makseq** [comment]
Hi, you have to use RectangleLabels to enable Yolo export. Yolo supports only bounding boxes (rectangles).

**Comment by ryouchinsa** [comment]
Using this script, you can convert the COCO segmentation format to the YOLO segmentation format.
https://github.com/ultralytics/JSON2YOLO

RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export the YOLO segmentation format.
https://rectlabel.com/help#xml_to_yolo
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
![yolo_polygon](https://user-images.githubusercontent.com/1954306/214472214-a9c2775d-247a-4bd1-87f6-9d90818ef8ff.jpg)

**Comment by makseq** [comment]
@ryouchinsa what labeling config do you use? Could you share it please

**Comment by ryouchinsa** [comment]
Thanks for your response.
For semantic segmentation with polygons, after labeling, we cannot choose the exporting YOLO option.
As you know, this is the YOLO segmentation format.
https://rectlabel.com/help#xml_to_yolo
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
Both YOLOv5 and YOLOv8 are popular training tools.
https://github.com/ultralytics/yolov5/releases/tag/v7.0
https://github.com/ultralytics/ultralytics

As a Label Studio user, we think you should correspond to the exporting option.

**Comment by makseq** [comment]
Thank you for your feedback, we will try to add a support soon.

**Comment by makseq** [comment]
Polygon segmentaion export is added to LS in the latest develop commits, will be delivered in v1.7.2.
https://github.com/heartexlabs/label-studio/pull/3628

**Comment by kawamucho** [comment]
We RectLabel team apologize that we answered to your issues from your users comparing with our product. 
We removed all comments which did not have any responses from your team.
Currently our comments are only in these 2 issues.
https://github.com/heartexlabs/label-studio/issues/3457
https://github.com/heartexlabs/label-studio/issues/3562

But for these 2 issues, your team added the YOLOv5 segmentation format, so that we believe that we could contribute to your community.
Currently @ryouchinsa is marked a spam account by your team.
Could you turn off the spam setting?
Please let us know your opinion. 

Best regards,
Ryo

**Comment by Rohan-Python** [comment]
How to export the shape file (In my case it is polygon not bounding box) from the detections? Can someone help please
Thank You...
