### ISSUE TITLE
Unable to install on M1 Mac

### ISSUE THREAD

**Issue by hamrickdavid** [heartexlabs/label-studio#3645]
**Describe the bug**
I'm not able to install label-studio locally I'm on laptop (M1 Macbook Pro). I am able to install it on a linux machine with the same procedure.

**To Reproduce**
1. Created a virtual environment `python3 -m venv env`
2. Activate virtual environment `source env/bin/activate`
3. Attempt to install label-studio `pip3 install label-studio`
4. Was given the error: `ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects`

When I install pandas directly with pip - it installs just fine.

**Expected behavior**
I expected to be able to install on macOS Ventura

**Screenshots**
![CleanShot 2023-02-02 at 17 36 54](https://user-images.githubusercontent.com/425856/216400143-44b353b9-00dc-45a4-b8af-6c5d0ba3afd3.png)

**Environment (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Label Studio Version: Latest - 1.7.1
 - Python version: 3.9.9 - also tried 3.7.12 and 3.8.10
 - Pip version: 23

**Additional context**
I also tried to use different python versions (3.7.12, and 3.8.1) and tried to install older versions of label-studio

Any idea what could be wrong? Is this likely a problem on my end or a problem with the dependencies?

**Comment by hogepodge** [comment]
I'm not able to reproduce on my M1 Mac. Can you help us determine which version of Python you're using? If you run `ls -l env/bin/python` that should tell you which version of Python is installed.

My system Python is 3.9.6, and my Homebrew installed version is 3.10.8. I was able to pip install label-studio using both. If you're installing Python from a different source (like Homebrew), you may need to update it.

Edit to say that I'm running Ventura 12.1, and that may be the issue (since you're running 12.2). I'll upgrade and report back.

**Comment by makseq** [comment]
Please use brew on mac:

```
brew install label-studio 
```

**Comment by hamrickdavid** [comment]
Thanks for the quick response. I was running pyenv and switching between python versions. I tried the system python and it seemed to work! Thanks for your help.
