### ISSUE TITLE
ML integration and predictions: ask for clarifications

### ISSUE THREAD

**Issue by ftesser** [heartexlabs/label-studio#383]
**Describe the bug**
Hi all, first of  thanks for this great software. This is not really a bug report, but a request for clarifications (e.g. updating documentation).

I followed this guide:

https://github.com/heartexlabs/label-studio/tree/master/label_studio/ml

and taking as reference the examples I created my own model for predictions.
The connection between label-studio and the ml backend work correctly.

However, I do not understand if the following is intended, or if I miss something from the documentation.
  
The ML prediction is triggered every time I try to open a task and it is stored in the completions section (not in the predictions).
Moreover if a completions is already present for that task, the ML prediction overwrites the old completion.

**Expected behavior**
1. I was expecting that the ML predictions was stored in the predictions sections 
2. Moreover I was expect that the prediction was triggered by a button (e.g. predict this task with ML model) and not triggered every time I open the task.
3. Finally (bonus): should be nice to have a batch procedure that run the ML predictions for all the tasks.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser chromium
 - Version 0.7.3

**Additional context**

**Comment by makseq** [comment]
Hi, it seems it's a bug - completions instead of predictions. Can you show a sample task json? @ftesser

**Comment by jeannefukumaru** [comment]
Hi, I have had a similar experience. This is the process I followed and the resulting `task.json`

1. Connect Label Studio UI to ML backend
2. Label data
3. Press Start Training button in `Model` page
4. Upload new data
5. Predictions from ML backend shows up as a pre-label
6. Hit `submit` button to confirm that the prediction is correct, or correct the prediction before hitting `submit` 
7. Export annotations as `tasks.json`

`tasks.json` shows the predicted tasks as a completion instead of a prediction 
![Screenshot 2020-08-21 at 3 36 01 PM](https://user-images.githubusercontent.com/26344607/90865157-8d2f3d80-e3c4-11ea-98a9-5da7f10073c3.png)

I think a recommendation in the slack channel is to add a field 
```
"enable_predictions_button": true,
```
inside the `project/config.json` also this method is still unofficial for the moment.

**Comment by makseq** [comment]
What behavior do you expect? 

When you are in labeling mode the prediction is copied to completion automatically and users always edit completions, not predictions. Because users can't produce predictions in LS paradigm. Predictions are immutable.

**Comment by ftesser** [comment]
Sorry for the late answer as well.
From my point of view the ML mode generate predictions so I was expected the `predictions` filed will be filled using the "ML backend" mode. Probably it is just different meaning of the word predictions.

But so, when the predictions` filed is used?

Additional question whats the "LS paradigm"?

**Comment by makseq** [comment]
> But so, when the predictions field is used?
It's used for two cases: 
1. ML backend generates them
2. User prepared a task with pre-labeling and user must save a pre-labeling to the prediction

> whats the "LS paradigm"
Predictions are not changeable: user is not allowed to change predictions via LSF.

**Comment by ftesser** [comment]
> > But so, when the predictions field is used?

> It's used for two cases:
> ML backend generates them


But then there is something strange, because I see only the completions in the json file. 
If as you say the "prediction is copied to completion" I expect to see both predictions and completions.
It could not be that the ML backend by mistake generates completions instead of predictions?

**Comment by makseq** [comment]
> It could not be that the ML backend by mistake generates completions instead of predictions?
No, it could not be.
