### ISSUE TITLE
copy-pasting of bounding boxes

### ISSUE THREAD

**Issue by undefdev** [heartexlabs/label-studio#395]
A lot of times bounding boxes within an image have very similar size, being able to copy and paste them would save a lot of time when annotating!

**Comment by NandaBalakrishnan** [comment]
is there any updates on the above feature?

**Comment by makseq** [comment]
We are on UX development stage for this feature right now.

**Comment by NandaBalakrishnan** [comment]
thank you

**Comment by makseq** [comment]
Check here: 
https://github.com/heartexlabs/label-studio/issues/512#issuecomment-751901429

So, you could try to copy bboxes now. 
Attention: it will work correctly only if you have widths & heights are the same for all images.
Otherwise you need to manually fix `original_width` and `original_height` for all the completion results.

**Comment by NandaBalakrishnan** [comment]
Sure will check and let you know.
