### ISSUE TITLE
Error in docs, missing `"Principal": "*",` in permissions for Amazon S3

### ISSUE THREAD

**Issue by jaanli** [heartexlabs/label-studio#4066]
https://docs.heartex.com/guide/storage.html#Amazon-S3 suggests using the following:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::<your_bucket_name>",
                "arn:aws:s3:::<your_bucket_name>/*"
            ]
        }
    ]
}
```

I edited this in this way:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::payless.health",
                "arn:aws:s3:::payless.health/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::payless.health",
                "arn:aws:s3:::payless.health/*"
            ]
        }
    ]
}
```

The permissions editor complained:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/5317244/233180608-50100503-887a-4a6b-9037-15a30eafbea5.png">

Adding in `            "Principal": "*",` fixed it:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::payless.health",
                "arn:aws:s3:::payless.health/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::payless.health",
                "arn:aws:s3:::payless.health/*"
            ]
        }
    ]
}
```

Not sure where to post small things like this, hope it's okay! Just want to help improve the docs :)

**Comment by farioas** [comment]
There are two main types of IAM policies:

`Identity-based policies`: These policies are attached to an IAM user, group, or role in your AWS account. In this case, the "Principal" field is not required because AWS can determine who the policy applies to based on the IAM identity it is attached to. These policies are used to grant permissions to users or roles within your own AWS account.

`Resource-based policies`: These policies are attached to resources (like an S3 bucket or a Lambda function) rather than an IAM user, group, or role. In this case, the "Principal" field is required to specify the AWS account, user, role, or federated user that the policy grants permission to. Resource-based policies are used to grant permissions to users or roles in other AWS accounts or to AWS services that need to access your resources.

In our instruction we have the following statement:
```
Assign the following role policy to an account you set up to retrieve source tasks and store annotations in S3, replacing <your_bucket_name> with your bucket name:
```

That's why `Principal` field is not required.
