### ISSUE TITLE
Set up persistent storage on Azure does not work

### ISSUE THREAD

**Issue by patcharees** [heartexlabs/label-studio#4310]
Hi,

I deploy Label Studio to Azure by using the template https://github.com/heartexlabs/label-studio/blob/develop/azuredeploy.json. Then I add these application setting to point to an azure storage account.

STORAGE_TYPE=azure
STORAGE_AZURE_ACCOUNT_NAME="<YOUR_STORAGE_ACCOUNT>"
STORAGE_AZURE_ACCOUNT_KEY="<YOUR_STORAGE_KEY>"
STORAGE_AZURE_CONTAINER_NAME="<YOUR_CONTAINER_NAME>"

But the Label Studio web app does not store anything on the storage account. When I restart the Label Studio web app, all created projects are gone.

Any suggestions?

**Comment by farioas** [comment]
Hi,

The issue template is designed specifically so that we waste less time asking questions. 
Please fill out the problem using the provided template and attach the application logs.

**Comment by Betty1202** [comment]
@patcharees Have you solved this problem yet? I meet the same problem when I use the lastest iamge.

**Comment by jovanbubonja-tomtom** [comment]
Hi @farioas ,

I was also trying to deploy Label Studio as an Azure Web App using the Deploy to Azure template. But also after the web app restarts everything is lost. I followed documentation [https://labelstud.io/guide/persistent_storage#Set-up-Microsoft-Azure-Storage](https://labelstud.io/guide/persistent_storage#Set-up-Microsoft-Azure-Storage) but without any success. 

But here [https://labelstud.io/blog/introduction-to-label-studio-in-hugging-face-spaces/#making-your-label-studio-hugging-face-space-production-ready](https://labelstud.io/blog/introduction-to-label-studio-in-hugging-face-spaces/#making-your-label-studio-hugging-face-space-production-ready) it says that Postgres database is needed for persistent storage.

It is all a bit confusing, could you clarify this a bit?

**Comment by bubonja** [comment]
Hi @farioas ,

I was also trying to deploy Label Studio as an Azure Web App using the Deploy to Azure template. But also after the web app restarts everything is lost. I followed documentation https://labelstud.io/guide/persistent_storage#Set-up-Microsoft-Azure-Storage but without any success. I have added all the variables to Web App -> Configuration page.

<img width="1725" alt="Screenshot 2023-08-14 at 14 47 46" src="https://github.com/HumanSignal/label-studio/assets/119058166/44ebfdee-c480-47fd-a04c-92eebc7007ea">

But then here https://labelstud.io/blog/introduction-to-label-studio-in-hugging-face-spaces/#making-your-label-studio-hugging-face-space-production-ready it says that Postgres database is needed for persistent storage.

It is all a bit confusing, could you please clarify this a bit?

**Comment by farioas** [comment]
All single-clicks buttons are just demo instances. They should not be used in a production environment, but they are sufficient for testing the application.

By default, Label Studio stores:
- All runtime data (users, settings, labels, etc.) in an SQLite3 database.
- All uploaded data (images, .wav files, .mp4 files) in the filesystem.

Due to architectural limitations of S3, Azure, GCS, and other similar services, using an SQLite3 database is not possible. Therefore, you should utilize a separate PostgreSQL instance for persistent runtime data storage.

**Comment by bubonja** [comment]
@farioas When I created Azure Database for PostgreSQL flexible server and added the postgres database connection details:

DJANGO_DB=default
POSTGRE_NAME=<postgres_name>
POSTGRE_PORT=<db_port>
POSTGRE_USER=<postgres_user>
POSTGRE_PASSWORD=<password>
POSTGRE_HOST=<db_host>

the start-up failed and produces these logs in Deployment Center:

```
2023-08-14T14:37:19.316Z INFO - Logging is not enabled for this container. Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2023-08-14T14:37:19.921Z INFO - Initiating warmup request to container ______ for site ______
2023-08-14T14:37:24.979Z ERROR - Container ______ for site ______ has exited, failing site start
2023-08-14T14:37:25.009Z ERROR - Container ______ didn't respond to HTTP pings on port: 8080, failing site start. See container logs for debugging.
2023-08-14T14:37:25.015Z INFO - Stopping site ______ because it failed during startup.
2023-08-14T14:37:33.715Z INFO - latest Pulling from heartexlabs/label-studio
2023-08-14T14:37:33.727Z INFO - Digest: sha256
2023-08-14T14:37:33.728Z INFO - Status: Image is up to date for heartexlabs/label-studio:latest 2023-08-14T14:37:33.732Z INFO - Pull Image successful, Time taken: 0 Minutes and 0 Seconds
2023-08-14T14:37:33.743Z INFO - Starting container ______ for site ______
2023-08-14T14:37:33.745Z INFO - docker run -d --expose=8080 --name ______ -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME= ______ -e WEBSITE_AUTH_ENABLED=False -e PORT=8080 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME= ______ -e WEBSITE_INSTANCE_ID=************ -e WEBSITE_USE_DIAGNOSTIC_SERVER=False heartexlabs/label-studio:latest label-studio
2023-08-14T14:37:33.745Z INFO - Logging is not enabled for this container. Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2023-08-14T14:37:34.320Z INFO - Initiating warmup request to container _______
2023-08-14T14:37:39.369Z ERROR - Container ______ has exited, failing site start
2023-08-14T14:37:39.382Z ERROR - Container ______ didn't respond to HTTP pings on port: 8080, failing site start. See container logs for debugging.
2023-08-14T14:37:39.387Z INFO - Stopping site ______ because it failed during startup.
```

As the POSTGRE_NAME I have provided the default database "postgres" that is created with Azure PostgreSQL and I have added a firewall rule to allow all ip adresses:
![Screenshot 2023-08-14 at 17 00 51](https://github.com/HumanSignal/label-studio/assets/119058166/72f77f05-e6b4-41a3-9260-15d89088c31a)

Can you please give me some more detailed steps of what I need to do to make it work?

**Comment by farioas** [comment]
I left the comments to the right:
```
DJANGO_DB=default # leave as default, do not change it
POSTGRE_NAME=<postgres_name> # put your database name
POSTGRE_PORT= 5432 # database port
POSTGRE_USER=<postgres_user> # put your database user, it should have enough permissions to create db and/or tables
POSTGRE_PASSWORD=  # put password if required
POSTGRE_HOST=<db_host> #ip address 
```

**Comment by bubonja** [comment]
So as the deployment logs suggested I followed the documentation [https://aka.ms/linux-diagnostics](https://aka.ms/linux-diagnostics) to enable and get container logs. There was a traceback with an error message:

```
django.db.utils.NotSupportedError: extension "pg_trgm" is not allow-listed for "azure_pg_admin" users in Azure Database for PostgreSQL
HINT:  to see the full allow list of extensions, please run: "show azure.extensions;"
```

It seems that in Azure Database for PostgreSQL all of these azure.extensions were disabled by default. All I did was go to my PostgreSQL instance -> then under Settings go to Server Parameters -> search for "azure.extensions" -> under VALUE there is a dropdown list with all extensions -> ticked all of the boxes -> then Save. The PostgreSQL instance restarted and I was ready to go.

Now the persistent storage feature works. After restarting the web app all credentials and project information were present.

**Comment by pietz** [comment]
Thank you for your feedback @bubonja . It allowed me to successfully setup the database. I do still struggle with the blob storage though:

Uploading images works and I can see them in Blob Storage. However, Label Studio doesn't load them afterwards in the UI. I did set up CORS as it's displayed on a screenshot in the docs for GET requests. The URLs to the images don't work but the path does match the folder structure of my blob storage.

Any ideas? Did you need to configure more stuff on the storage account?

**Comment by bubonja** [comment]
@pietz I've set up the CORS rule as docs suggest [Configure-CORS-for-the-Azure-bucket](https://labelstud.io/guide/persistent_storage#Configure-CORS-for-the-Azure-bucket).

Also check if you've set up all the environment variables properly. Although you've set up source and target cloud storage in project settings, you still need to add AZURE_BLOB_ACCOUNT_NAME and AZURE_BLOB_ACCOUNT_KEY as environment variables.

**Comment by pietz** [comment]
@bubonja thanks for your quick reply. I believe, I did all that. AZURE_BLOB_ACCOUNT_NAME/KEY and STORAGE_AZURE_ACCOUNT_NAME/KEY can be the same values right? I simply created different containers for them.

It sounds like you treat application settings and env variables differently. I just have them all in here like this:

<img width="907" alt="Screenshot 2023-09-04 at 18 44 34" src="https://github.com/HumanSignal/label-studio/assets/13137132/caa50d87-eb1a-4205-84f5-628a2954c5de">

Am I missing something?

**Comment by bubonja** [comment]
@pietz I added connections to containers through UI, I didn't specify them through application settings. Sorry for these dumb tips, but maybe they are worth a try. Are you getting any errors in the UI? Also, in Project Settings -> Cloud Storage there is a button to sync contents of container to your project after you specify connection parameters.

**Comment by pietz** [comment]
@bubonja Thanks again for your help. I really appreciate it. Sadly, I wasn't able to make it work. I found another way though, which might be better for some people. It's definitely simpler than the way suggested here:

1. Do the One-Click Deployment to Azure. I use a `B3 SKU` which costs roughly 48€ per month.
2. Create a Storage Account File Share. I used the `transaction optimized` since it sounded best for my needs.
3. Connect your App Service to the File Share under Configuration > Path Bindings. I mounted mine under `/data`.
4. Create an Application Setting called `LABEL_STUDIO_BASE_DATA_DIR` with a value of `/data`.

That's it. Label Studio will create the SQLite database under /data together with the data files. The persistent storage will keep everything when the server restarts. In theory, this could be slower than a dedicated Postgres DB. However, in my testing it feels very snappy. Definitely faster than the Huggingface deployment and maybe even faster than the Postgres in my quick testing.

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved using the workaround.

**Comment by GillesJ** [comment]
@pietz I used your setup and it works pretty good. Loading large .json task files for my large documents is quite slow, but it's acceptable and I haven't tested if a PostgresDB deployment would be faster.

Updated Azure for October 2024 after some Azure service renaming and interface changes:

1) Do the One-Click Deployment to Azure (B1-B3 seem fine to do the project setup work, scale up when more annotators or tasks).
2) Create a Storage Account at the setup screen select as Primary Service: `Azure Files` (rename from Azure File Share), Performance type: `Premium` because we need low read-write latency.
3) Setup a File share within the Storage Account: Within portal for Storage Account resource > Data storage > create File share + Fileshare
4) In the App Service of Labelstudio > Configuration > Path Mappings tab > + New Azure Storage Mount and configure AzureFiles under `/data`
5) In the App Service under Settings > Environment Variables creeate an App setting env var `LABEL_STUDIO_BASE_DATA_DIR` with value `/data`
