### ISSUE TITLE
Current latest docker tag does not contain linux/arm64 build

### ISSUE THREAD

**Issue by JFKingsley** [heartexlabs/label-studio#4331]
**Describe the bug**
Your current docker latest build does not have an attached linux/arm64. Other builds, and past builds do have this. This results in my being unable to install Label Studio on Apple Silicon.

**To Reproduce**
1. Run docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest
2. "docker: no matching manifest for linux/arm64/v8 in the manifest list entries."

**Expected behavior**
A complete docker install!

**Environment (please complete the following information):**
 - OS: macOS 13.4
 - Label Studio Version: Unknown

**Comment by farioas** [comment]
We have been aware of this ongoing issue since April 8, specifically after switching to `node:18`, which caused problems with yarn2 builds for arm architecture. This is a well-known issue involving QEMU and yarn: https://github.com/nodejs/docker-node/issues/1335.

Unfortunately, we were unable to address and implement a fix prior to the release 1.8.0. However, I am glad to inform you that we have resolved all the issues today. We have updated all the images to include arm builds, ensuring compatibility with Apple Silicon.

Thank you for bringing this issue to our attention.
