### ISSUE TITLE
Cannot link to image after add source storage 

### ISSUE THREAD

**Issue by dinhthihuyen** [heartexlabs/label-studio#4485]
**Describe the bug**
I have images in folder: '/home/anna/images'. I add source storage '/home/anna/images', but cannot display image through link 'localhost:8080/data/local-files/?d=images/image_1.jpg'

**Comment by erinmikailstaples** [comment]
Hey @dinhthihuyen — thanks for sharing!

Because of our privacy settings and to ensure that your data stays on your machine, we'll surface a file path vs. displaying the image itself.  Therefore, behavior is as expected for your output. 

Let me know if you have any further questions or if I can help in other ways.

 [Join Slack Community for further discussion](https://slack.labelstud.io/?source=GitHub).
