### ISSUE TITLE
Data Sync with Oracle Cloud Infrastructure (OCI) Bucket Stuck in Queue

### ISSUE THREAD

**Issue by magsasaka1** [heartexlabs/label-studio#4557]
**Describe the bug**
I am trying to add an Oracle Cloud Infrastructure (OCI) bucket as a cloud storage using the AWS S3 option (since, OCI bucket is S3-compatible). However, the data synchronization status is stuck at "Queued". There are no error messages displayed, and I haven't found any relevant information in the logs to indicate the root cause of the issue.

**To Reproduce**
1. Set up OCI bucket.
2. In Label Studio, navigate to **Settings**.
3. Then, navigate to **Cloud Storage**.
4. Click **Add Source Storage**.
5. Select **AWS S3** as cloud storage type.
6. Provide the necessary details including the endpoint, bucket name, and access keys.
7. Click on **Check Connection**. It should show **Successfully Connected**
8. Then, click **Add Storage**.
9. After adding storage, you should now be able to **Sync Storage**.
10. However, the status then gets stuck at "Queued" status without progressing.

**Expected behavior**
I expected the data in the OCI bucket to be imported into Label Studio successfully.

**Environment (please complete the following information):**
- OS: installed Label Studio in Ubuntu
- Browser: I am running the Label Studio interface in Edge
- Version of Label Studio: latest version

**Additional context**
I understand that OCI does not support Cross-Origin Resource Sharing (CORS) even though it is S3 compatible, which might be causing the issue. However, as I have not received any error messages, I am unable to verify this. I would greatly appreciate any assistance in resolving this issue or confirmation of whether it's related to the lack of CORS support in OCI.

**Comment by erinmikailstaples** [comment]
Hey @RsdNoob — thanks for letting us know.

Have you checked your logs? We'd be happy to take a peek if you drop them here in the comments. 

Depending on how you're running it you can find it in the docker logs or in the terminal window.

Otherwise, unfortunately, we cannot reproduce because OCI is not an official supported integration at this given time. 

I'd love to have you submit a feature request if you'd like this to be an official supported integration. :)
