### ISSUE TITLE
Easy way to import a label-studio project/dataset

### ISSUE THREAD

**Issue by Sijie-L** [heartexlabs/label-studio#4722]
Hi. Is there a way to share a label-studio project (i.e. image+annotation) smoothly from one device to another?

Specifically, I have uploaded images and label configurations to the server. But since it is already heavy-loaded, it is better to annotate it locally and then upload it back to our server. I know I can use the result label file directly, but small refinements on the server are also needed. I did check this [page ](https://labelstud.io/guide/predictions.html#Example-of-importing-predicted-labels)guiding you on how to load pre-annotated data, but it looks SO COMPLICATED. I mean, I just want to share the label-studio annotation and image from the local to the server, without any modification or conversion. Couldn't I just do something like export the images and json file from the UI, and then import them again to label-studio on another device? 

Any tips or help would be appreciated. It would make my life easier. Thanks in advance.

**Comment by g-piana** [comment]
Hi. I have the same exact problem, which I also submitted on the Slack channel without getting any support.
I must transfer a whole project (images and annotation) to a different server.
The project duplication (export the full JSON) and then import in a new project works fine on the same server only, I could not make it work across two servers. The problem is that the JSON with annotations references the image with a local path such as:
"data":{"image":"\/data\/upload\/66\/7f58fbc7-CV_02_IM_0001_0042_0001_000020.jpg"} and then a unique identifier id which (I guess) is specific to the local sqlite database, both obviously working only on the original server. 
In the new server, we should be able to upload images first possibly forcing the same id unique identifier (which is dangerous), and then upload the annotation json from the old server where the unique id is used as key to update the annotation of the correct image in the sqlite of the new server.
On one hand I see it's quite challenging to do that playing with the current json export.
On the other hand it seems to me such a common, basic need that I wonder whether a simpler approach is currently used, something simple that do no require setting up a web server or jumping through twenty hoops. The COCO export option seems promising but again no way of importing into a different server, which is very strange.
Let me know if you find anything useful. Hope somebody more experienced with LS can show the path to a simple solution

**Comment by Sijie-L** [comment]
Hi, piana. I managed to make it work, but I wouldn't say it is an easy way. The following is how I reimport my custom dataset, I hope you find it useful.

My goal is to reimport an object detection dataset with annotated rotated bounding boxes. To this end, I exported the YOLO and JSON-min format files from the original project.

1. Set environment variables. (LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED and LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT)

2. Use label-studio-converter to create JSON files. e.g.

```
$ cd [yolo_export_dir]
$ label-studio-converter import yolo -i . -o test.json 
```
You will get two files: test.json and test.label_config.xml
(I did realize the path in the test.json is not correct here, but I didn't manage to generate the right one. So I wrote a python script to handle that in a later step.)

3. Create a new project on label-studio and set labels by copying the contents in test.label_config.xml.
4. In Settings->Cloud storage, click Add Source Storage and select Local files. In the Absolute local path, fill in the absolute path of the [yolo_export_dir]/images. Click Add Storage and done. 
Do not toggle on the "Treat every bucket object as a source file" button and do not click "Sync storage". Just leave it like that..
5. There are two problems with the test.json file: 1) the path is not correct, and 2) in my project, I also need the rotation information, but the YOLO format output file doesn't include that. 
To fix that, I wrote a python script ([yolo_complete_the_path.txt](https://github.com/HumanSignal/label-studio/files/12923593/yolo_complete_the_path.txt)). It managed to:
  (1) Modify paths from "/data/local-files/?d=/image.jpg" to "/data/local-files/?d=[relative_path_from_LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT]/image.jpg" 
  (2) Modify bbox info when the rotation value in the JSON-min file is not 0.
6. Get back to your label-studio project, and import the modified test.json file. It should be able to load both the images and the annotations now🙂

**Comment by dceluis** [comment]
I used import yolo -i ~/Downloads/vaco-yolo/valid -o valid.json --image-root-url "/data/local-files/?d=workspace/vaco-dataset/source"

to fix `relative_path_from_LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT`. For future reference, if anyone is having this issue of incorrect paths to the local files.

**Comment by g-piana** [comment]
Hi, Thank you for following upI managed to make it work in a similar fashion. I had to write a script to create a different json to import as prediction though.G  Giulio Piana, PhDFounder and Chief AI scientistMobile: +39 335 777 8194     From: SijieSent: 17 October 2023 03:55To: HumanSignal/label-studioCc: Giulio Piana; CommentSubject: Re: [HumanSignal/label-studio] Easy way to import a label-studio project/dataset (Issue #4722) Hi, piana. I managed to make it work. But I wouldn't say it is an easy way. The following is how I reimport my custom dataset, I hope you find it useful.My goal is to reimport an object detection dataset with rotated bounding boxes. To this end, I exported the YOLO and JSON-min format of the original project.Set environment variables.Use label-studio-converter to create JSON files. e.g.$ cd [yolo_export_dir]$ label-studio-converter import yolo -i . -o reimport.json You will get two files: test.json and test.label_config.xml3. Create a new project on label-studio and set labels by copying the contents in test.label_config.xml.4. In Settings->Cloud storage, click Add Source Storage and select Local files. In the Absolute local path, fill in the absolute path of the [yolo_export_dir]/images. Click Add Storage and done.5. Do not toggle on the "Treat every bucket object as a source file" button and do not click "Sync storage". I don't know what they exactly do but it doesn't work in my case.6.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Vadim2S** [comment]
A little clarification about the workaround described above:

Task: Transfer a dataset with annotations from one server to another.
Server1: LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT = /Path1/, Local cloud storage with the path - /Path1/folder1.
Server2: LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT = /Path2/

Solution: 
1) On Server1, export annotations to JSON format.
2) Create a subfolder on Server2 with the **same name** as the subfolder on Server1 (folder1 here). The Path1 and Path2 may differ.
3) Create a dummy new project on Server2 and create Local cloud storage with the path /Path2/folder1. Test it, but **do not** synchronize it. This project and storage is only for Label Studio to know about folder1's existence.
4) Create your real new project on Server2 and import the file in JSON format

P.S. Two projects were created to protect against errors. If you import JSON **and** synchronize the storage, you get a double set of tasks.
