### ISSUE TITLE
Issue importing data from url

### ISSUE THREAD

**Issue by Reasat** [heartexlabs/label-studio#4764]
**Describe the bug**
I am trying to add image data residing in the public domain. But I get this error in 
![image](https://github.com/HumanSignal/label-studio/assets/15989033/7d1a239d-bd87-4269-a636-8bd14f98bf3d)

I can go to the actual image when I click the url given in the screenshot.

My labeling interface looks like this

![image](https://github.com/HumanSignal/label-studio/assets/15989033/24b9f3c8-ea6a-41ea-8758-bf3b33f8020a)

 - OS: Linux
 - Label Studio Version 1.8.1

Any help regarding this is appreciated, thanks!

**Comment by frippe75** [comment]
I have the exact same issue from what I can tell. I have been going nuts over this. Deployed on GKE and exposed via ingress using TLS from letsencrypt.

I cannot figure this one out. On slack at channel "13-support-other" discussing this.

> Again. Tracing via browser. I see the request for the mp4 file. Right-clicking on it and saving the request as a curl. That curl sucessfully downloads the mp4 as well.

**Comment by hogepodge** [comment]
@Reasat can you share the sample dataset that you're loading that image with? I'd like to reproduce the issue so I can file a bug with the engineering team.

**Comment by frippe75** [comment]
Simply followed the GKE installation, added a single mp4 file and selected the Object detection template for labeling.  And just like the issue creator added TLS certificate and exposed the UI via an Ingress controller. Nothing more. So not using any dedicated S3 storage but the built in.

My label-studio-values.yaml:
https://pastebin.com/b6SfQZSL

**Comment by frippe75** [comment]
But searching for CORS and Label Studio indicates this is somewhat of a repeating story. Traced the failed GET against the /data URI and I can't really find anything at fault there. More leaning towards the thrown error being incorrect. No CORS errors in the console/network tabs under Chrome dev-tools. Tried Firefox as well just to see if the browser could be the culprit.

The GET actually lead to a 200 but looks like the browser (js-script) does not follow through on the GET and the reponse looks empty

If I select the request in the browser dev-tools and copy the entire request with all headers, cookies and so on as a curl-request and do it via the terminal the mp4 file is downloaded. So the backend seems to work...

As I said the error is not visible at browser-console level but rather picked up in js-code and displayed via the app.

**Comment by frippe75** [comment]
For me the failed URI is actually not:
**https://ls.*****.io/data/upload/1/***.mp4**

But rather:
/data/upload/1/***.mp4**

I wonder if simply js client side logic for detecting "CORS" issues is doing something "smart" here?

**Comment by frippe75** [comment]
Interesting feature flag:
fflag_fix_all_lsdv_4711_cors_errors_accessing_task_data_short

**Comment by frippe75** [comment]
Hmm could this be the instrumented fetch via the sentry package?? Not sure I'm able to trace this correctly.

**Comment by hogepodge** [comment]
@Reasat this is an issue with the server that you are trying to load the image from. The host server, in this case, https://webpath.med.utah.edu, has a policy that prohibits web apps not hosted on their domain from loading resources into their interface. When you load the image directly into your browser, you can see it because it's being loaded directly from the domain, but in Label Studio it's being requested through the domain that Label Studio is hosted from, and the remote server is prohibiting the file from being loaded.

I was able to confirm this with a simple test project, and looking at the error in the console from Chome.

```
Access to image at 'https://webpath.med.utah.edu/jpeg3/BREST092.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Unfortunately, there's nothing we can do to resolve this from Label Studio. This is based on security policies enforced by the host server of the image.

**Comment by frippe75** [comment]
I don't think you understand the issue here. I'm seeing the same issue with labestudio trying to pull the data from it's self hosted under /data/upload. Simply closing issues dont resolve them

**Comment by frippe75** [comment]
And what @Reasat probably meant about public was that it's a labelstudio they have exposed using public addresses.

**Comment by hogepodge** [comment]
You would do well to familiarize yourself with CORS. There are two issues at play here. The first is that modern browsers, by implement a Same-Origin Policy.

"The Same-Origin Policy permits the browser to load resources only from a server hosted in the same-origin as the browser... In the absence of the Same-Origin Policy, any scripts downloaded from cross-origin servers will be able to access the document object model (DOM) of our website and allow it to access potentially sensitive data or perform malicious actions without requiring user consent."

As Same-Origin Policy was too restrictive, CORS was developed to give servers a way to signal to browsers which resource could be safely loaded in a cross-domain policy. While "the CORS protocol is enforced only by the browsers. The browser does this by sending a set of CORS headers to the cross-origin server which returns specific header values in the response. Based on the header values returned in the response from the cross-origin server, the browser provides access to the response or blocks the access by showing a CORS error in the browser console."

You need to either disable the CORS restrictions in your browser, set a server-side policy on the server hosting the image that indicates to the browser that loading the cross-origin resources is allowed, or use a proxy to the resources.

This is not an error with Label Studio, rather it is the open-source version of Label Studio running into the limitations of web standards designed to protect the privacy and security of users. I drew the above quotes from [this article](https://reflectoring.io/complete-guide-to-cors). I encourage you to read it and understand the limitations and how to work around them.

If you're running into issues with serving local files, it may be because of URL mismatches.

I'm sorry that you're running into CORS issues, but Label Studio is behaving as expected given the configuration, and this is not a bug.

**Comment by Reasat** [comment]
@hogepodge sorry I was a bit busy was not following the thread. Thanks for looking into it and thanks for the clarifications!
