### ISSUE TITLE
Label Studio Kept Crashing on GCP 

### ISSUE THREAD

**Issue by d-c-a-i** [heartexlabs/label-studio#4913]
Hi, I have set up label studio on GCP by following the "Deploy in a cloud instance" section in README.md. 
I've successfully setup label studio and it was running without any problem. Now after I successfully connected GCP bucket with Label Studio project, the project kept crashing and I was then directed to the login page. I've then tried to signed in multiple times but still can't get in. I am not sure if the issue comes from connecting the GCP bucket with the Label Studio project. Can someone please give me some pointers? Thank you!

**Comment by jombooth** [comment]
I have an idea that may help, though it's just a guess. Often when you're getting redirected to the login page it's because your session has been invalidated. And since you've deployed Label Studio in the cloud, your deployment may not have a stable filesystem for our code to persist a random Django `SECRET_KEY` value to, and a secret key mismatch would lead to an invalidated session.

Could you try setting `SECRET_KEY` to an appropriate random string in your server's environment on GCP, if you haven't already, and see if that helps? Otherwise, I think our best bet for debugging would be to look for stacktraces in your instances' logs.

**Comment by jombooth** [comment]
Closing for now, please reopen if you're still running into issues!
