### ISSUE TITLE
JSON dir storage not working correctly

### ISSUE THREAD

**Issue by nopper** [heartexlabs/label-studio#495]
**Describe the bug**

I am using the latest stable version of label-studio(0.8.1) and I am experimenting with `dir-jsons` as tasks storage and found out that it's not well supported or properly documented.

If I follow the documentation at https://labelstud.io/guide/tasks.html#Directory-with-JSON-files I get the following:

```
$ mkdir tmp && label-studio init --input-path=$PWD/tmp --input-format=json-dir test
$ grep source -A 3 test/config.json
  "source": {
    "name": "Tasks",
    "type": "tasks-json", #  <----
    "path": "<REDACTED>/test/tasks.json"
```

But I am expecting the output to be:
```
  "source": {
    "name": "Tasks",
    "type": "dir-jsons", # <-----
    "path": "<REDACTED>/test/tasks.json"
```

Anyway after manually fixing the `config.json` file I see that there is an error in the Tasks view:

```
Project loading error
object of type 'generator' has no len()
Traceback

Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/label_studio/utils/misc.py", line 91, in exception_f
    return f(*args, **kwargs)
  File ".../lib/python3.8/site-packages/label_studio/blueprint.py", line 317, in tasks_page
    serialized_project = g.project.serialize()
  File ".../lib/python3.8/site-packages/label_studio/project.py", line 940, in serialize
    'task_count': len(self.source_storage.ids()),
TypeError: object of type 'generator' has no len()
```

**Comment by niklub** [comment]
Hi, @nopper !

The `"source"` key in `config.json` points to the storage from where your tasks are taken during the runtime (for the local file system it is `tasks.json` by default. This storage could be different from where you import your data (directory `$PWD/tmp` with JSON files in your particular case). So `"type": "tasks-json"` is expected, and is not intended to be modified (that's why you probably get an error).
I've tried to import data from directory with JSON files (structured as `{"text": "one two three"}` in each `tmp/file.json`) with the following command:
```
label-studio start my_project --input-path tmp/ --input-format json-dir --label-config label_studio/examples/text_classification/config.xml --init
```
and it works fine. Please reopen this issue if you'll encounter any runtime problems with your import.

**Comment by nopper** [comment]
Hi @niklub,

Thanks for the fast turn around. I am a little bit confused then.

Maybe it's easier if I explain to you my use case: I have another program that say daily, creates a series of tasks to for label-studio. For the moment I was writing them down as json files in a directory.

How can I get label-studio to detect these new tasks and load them? Before that I was merging all the tasks in a single json file but it's less convenient and error prone.
