### ISSUE TITLE
Error syncing with google cloud storage

### ISSUE THREAD

**Issue by aivatoglou** [heartexlabs/label-studio#5152]
**Describe the bug**
When attempting to sync Label Studio with Google Cloud Storage to process tens of thousands of JSON files/tasks, the following error occurs:

```
Error logs for gcs storage 1 in project 2 and job null:

It appears the job was failed because the last ping time is too old, and no traceback information is available.
This typically occurs if job was manually removed or workers reloaded unexpectedly.

meta = {"attempts":53,"duration":180.145198,"time_queued":"2023-12-05 15:01:59.086706+00:00","tasks_existed":31245,"time_last_ping":"2023-12-05 15:04:59.241041+00:00","time_in_progress":"2023-12-05 15:01:59.095843+00:00"}
```

**To Reproduce**
1. Sync Label Studio with Google Cloud Storage.
2. Attempt to process tens of thousands of JSON files/tasks.

**Expected behavior**
The syncing process should handle the large volume of tasks without encountering the "last ping time too old" error.

**Environment (please complete the following information):**
 - Label Studio Version 1.9.2

**Comment by manoadamro** [comment]
I have the same when syncing local files. It seemed to be marked "failed" when I changed tab and then went back to Cloud Storage.
Interestingly, because I'm using local files, I can see in resource monitor that all the folders it should be reading are being read from one by one, even though the task has been marked failed. 

Perhaps it will eventually complete, I'll add an edit to this with the result once it's got to the end.

---


Edit: It did eventually complete

**Comment by aivatoglou** [comment]
Unfortunately it never progresses beyond the 'Failed' state for me. Every time I attempt to 'Sync Storage' again, only a few hundred more items are loaded (or no new ones at all) before it fails once more.

**Comment by makseq** [comment]
```
"duration":180.145198
```
Label Studio Community doesn't have background processes and the time per job is limited by your wsgi worker timeouts.  The duration of 180 sec looks topically for it. You can try extend the wsgi timeout using [harakiri parameter](https://github.com/HumanSignal/label-studio/blob/develop/deploy/uwsgi.ini#L93C10-L93C31).
