### ISSUE TITLE
Improve task pagination

### ISSUE THREAD

**Issue by jonorozcoc** [heartexlabs/label-studio#522]
**Is your feature request related to a problem? Please describe.**
If you have many tasks imported and you want to go to the end (for example), you have to press the Next button until you reach the last page. On every Next button click all the images (in my use case, bbox tagging) are requested but not visualized because I already pressed the Next button again. And so on until the end

**Describe the solution you'd like**
In order to reduce requests and improve navigation speed I suggest to add a timeout in order to know if the user is not "fast navigating" and then request the images of the page

**Comment by makseq** [comment]
@jonorozcoc We have released a new data manager (but it's a release candidate now). Could you try it? I hope you'll like it.
Note: use google chrome, safari is not yet supported.  

```
pip install label-studio==0.9.0rc1
```

**Comment by jonorozcoc** [comment]
@makseq I reviewed the last version you mentioned. First at all thanks for your work and this excellent project. I have some question about the UX of this new data manager interface.

1. I saw you implemented infinity scrolling for listing the tasks. Taking in account that datasets involved in ML are large (really large in some cases) ¿How this can affect performance? When user scrolls down more data will be in JS memory heap and the app will be frozen, sluggish or even unresponsive. Tables don't have this issue as you can imagine because the data in memory is reduced to the pagination
2. I also saw you implemented lazy loading (for images, i don't know if it's similar to other data types), ¿Is it necessary to release or destroy previous visualized images? I noticed that the images are reloaded when the user scroll up. ¿Is it something related to the first point? (aka performance) and ¿how this can affect the server due to the increased amount of requests?

**Comment by makseq** [comment]
@jonorozcoc thanks for your questions. The common answer: for opensource we focus on datasets about 100k tasks. We've tested it on old machines with such datasets and it works well. I think 1m dataset will perform fast if you deploy LS on powerful server.

1. Browser stores only json data for all data set tasks without BLOB media files. So, it might not be huge in memory. Media files are stored only for the current page of infinite list.
2. Images and other media will be destroyed automatically, when they disappear from the current page of infinite list.
3. We are working on database replacement from file system to sqlite. So, it will change the server performance in better way.

**Comment by jonorozcoc** [comment]
Fair enough for me

**Comment by nicholasrq** [comment]
@jonorozcoc in addition to @makseq's answer I just wanted to clarify the mechanism.

for the infinite list we're using what's called "virtualized list". basically it's a mechanism when your viewport limits the amount of data. only the data you see on the screen exists physically on the page. we tested this approach on tens of thousands of tasks and there's no significant or anything noticeable performance drop. also we assume that nobody's gonna load all the data they have into browser's memory :) still, DM can handle a pretty large amount of data (depends on how much RAM you have, obviously)

as we're rendering only the data that fits into your viewport, we can optimize images load (and any media, actually). speaking of extra requests, thanks to browsers cacheing mechanisms, anything that has been loaded previously, will not require additional requests. all the media will be restored from cache instead of loading it from the server

**Comment by jonorozcoc** [comment]
@nicholasrq Thanks for your response

I guess it's something related to the Intersection Observer API isn't? (Just curiosity)

**Comment by nicholasrq** [comment]
@jonorozcoc not really. all tasks in the table has fixed height. we're tacking scroll offset to calculate the index of the first item, and how many items can fit into the viewport. after that we're adding 30 items before and after these indexes to avoid blinking during the render

e.g., your viewport can fit 15 items, so we'll render 75 of them: 15 are visible in the viewport +30 items up and 30 items down. that allows you to scroll very fast with almost not noticing the render lag
