### ISSUE TITLE
storedata problem

### ISSUE THREAD

**Issue by zwangZJU** [heartexlabs/label-studio#5272]
**Describe the bug**

I have deployed a standalone minio. How do I configure the environment variables so that labelstudio can connect to minio

**Comment by hogepodge** [comment]
Hi @zwangZJU I'm checking on the current status of minio in Label Studio. Since minio attempts to replicate an S3 endpoint, you should be able to configure the S3 cloud connector to use your minio endpoint. Since this isn't a bug, I'm going to close the issue. We can help you out more in the community slack.
