### ISSUE TITLE
ML Backend reload model and throw an error when I click the submit button

### ISSUE THREAD

**Issue by EtAiorsW** [heartexlabs/label-studio#5292]
Hi, I use my own yolo backend, when I add a machine learning backend, the model will be loaded into gpu, then it will start to inital infer. Everything goes well so far.

![ML](https://github.com/HumanSignal/label-studio/assets/44608797/d853f3b8-8b92-48e5-ad99-a1374faeed8a)

But if I open an image, and click the submit button, the backend will load model again with another process, and throw an error.

![log](https://github.com/HumanSignal/label-studio/assets/44608797/3708ad2a-66b0-48ba-9f6d-478884feebf0)

the repeated process will be killed in one second due to the error above

![nvidia-smi](https://github.com/HumanSignal/label-studio/assets/44608797/992f2508-9a60-48e8-97fd-f7354de39d3a)

**Expected behavior**
any idea about that

**Environment (please complete the following information):**
 - OS: ubunut 22.04.3 
 - Label Studio Version: 1.10.0
 - Label Studio ML Backend Verssion: 1.0.9

**Comment by hogepodge** [comment]
HI @EtAiorsW thanks for reporting this. It's difficult for us to completely diagnose the issue since we don't have access to the custom code you're working with.

My intuition is that the GPU is somehow being locked by the initial process/thread, and when the second process arrives, the newly created process/thread creates the GPU resource again but can't access that lock (but that's really just my best speculation, given the available information). 

As for solutions, it's hard to say. I would be looking for a solution where the GPU is attached to an independent process with a task scheduler in front of it. This would allow the backend to take multiple requests in batches and spread the work out.

If you can share your code and findings in the Slack channel, I think that community members will be able to offer their own expertise and guidance. I'm going to close this since it's not necessarily a bug with the backend, but more of a support question.

**Comment by EtAiorsW** [comment]
Thank you for your reply and suggestion, I will check my code, try to find the reason and then update this thread if there is any progress. When I have enough time, I will share my code. 
Thanks to your team for the great work.
