### ISSUE TITLE
Can data upload support pdf and word? Currently, only txt is supported.

### ISSUE THREAD

**Issue by yysturdy** [heartexlabs/label-studio#5589]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deppp** [comment]
You'd import those as URLs and embed viewing those documents using HyperText tag. Take a look at "Rate PDF" example in Playground: https://labelstud.io/playground/

**Comment by pbanuru** [comment]
@deppp How should we import the URLs with the embed?

For example,
I'm seeking:
```
{
    "pdf": "<embed src='https://app.heartex.ai/static/samples/sample.pdf' width='100%' height='600px'/>"
}
```

I tried saving a text file containing just: 
`<embed src='https://app.heartex.ai/static/samples/sample.pdf' width='100%' height='600px'/>` as "sample_pdf_url.txt" 
and importing it.

However, it shows up like this:
```
{
    "pdf": "/data/upload/1/4de68584-sample_pdf_url.txt"
}
```

Is there a way to ensure the embed tag itself is read and displayed instead of just showing the file path? Thanks!

**Comment by pbanuru** [comment]
I found the solution!:

solution is to put the entire:
```
{
    "pdf": "<embed src='https://app.heartex.ai/static/samples/sample.pdf' width='100%' height='600px'/>"
}
```
in a .json file, and import it.

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
