### ISSUE TITLE
Local File Upload Does not work - URL does not work

### ISSUE THREAD

**Issue by mechmehmet** [heartexlabs/label-studio#6173]
**Describe the bug**
I followed the instructions on doc and this video 

https://www.youtube.com/watch?v=lo6ncQajbdU

![image](https://github.com/user-attachments/assets/39e31e13-f0f6-4592-ad9d-7754aca14d14)

but the json file method does not work. I did not understand the problem.
![image](https://github.com/user-attachments/assets/f4adf5d8-475d-4390-a2b7-0d7701093cf6)
![image](https://github.com/user-attachments/assets/2053d085-ea7f-4a86-ab1d-0c294cbdd065)
![image](https://github.com/user-attachments/assets/07955b9f-effe-4ee2-b27a-45401babd47a)

 http://localhost:8080/data/local-files/?d=c:/calismalar/IMG_5200_435.jpg

and I tried to use "Treat every bucket object as a source file" this button and
![image](https://github.com/user-attachments/assets/0a13fbc8-9a83-42e7-b0ac-18591f75958c)
and pressed sync storage, it looks like this 
![image](https://github.com/user-attachments/assets/a3de3ff0-0381-4869-ab00-e18106562311)
but this time is also I can not see the images
![image](https://github.com/user-attachments/assets/1027f990-b7d1-4724-a0cf-baf98fb515e4)

[/data/local-files/?d=calismalar%5CIMG_5200_437.png](http://localhost:8080/data/local-files/?d=calismalar%255CIMG_5200_437.png)

How should I edit the URL

**Environment (please complete the following information):**
 - OS: Windows 11
 - Label Studio Version [1.13.0]

**Comment by mechmehmet** [comment]
I solved the problem.
![image](https://github.com/user-attachments/assets/e9b7207f-8525-4cf0-86c4-e510e37862f2)
this is the main problem which I have done.

If you are using Windows, ensure that you use backslashes when entering your Absolute local path.

before that I arrange the url like: "c:/calismalar"
but I have to use like: "c:\calismalar"

![image](https://github.com/user-attachments/assets/8772b241-ca57-4ad0-b81f-a9d0f6848283)

and another problem I used to accured is system enviroment. 
you should create a new system environment for LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT and LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED

![image](https://github.com/user-attachments/assets/353e2b56-f31c-4bc0-898d-66f629bd813c)

have a greate day

**Comment by jombooth** [comment]
Hi @mechmehmet - glad you were able to resolve, and thank you for posting your solution!

**Comment by aurexav** [comment]
You save my life...

**Comment by aurexav** [comment]
> Hi @mechmehmet - glad you were able to resolve, and thank you for posting your solution!

I believe this must be included in the doc site.

**Comment by joseph-jomon** [comment]
Thanks for the answer. The details explanation helped me
And a note that i would like to add is that  while using docker compose on windows(first of all read the docs for compose with local files )[https://labelstud.io/guide/start#Run-Label-Studio-on-Docker-and-use-Local-Storage]
1) mount the volume inside of the container
2) set the env variable LABEL STUDIO LOCAL FILES DOCUMENT ROOT
3) Remember after  step 2 when you import data from local files(here inside the mounted volume) to set the path relative to this path.(Settings-Cloud-Storage-Storage_type-local-files)
4) Click on save or also check connectioon
5) Depending on your folder structure if the dataset is nested choose treat every bucket object as a source (valid for local storage too not only for buckets in a cloud service)
6) And finally press the Sync Storage button 
7) if step 6 is successful then you can see the corresponding paths generated for your dataset in the dash board and these are the paths you should use in the json task file that you upload ,so that label studio has access to these files
