### ISSUE TITLE
Slow UI response times after ML backend connection

### ISSUE THREAD

**Issue by atakanokan** [heartexlabs/label-studio#632]
**Describe the bug**
UI response have slowed down very much after connecting a ML backend to the annotation project. Disabling the ML backend doesn't make response times return to normal.

**To Reproduce**
1. Create a new annotation project
2. Open a task -> fast (<0.3 seconds)
3. Create a new ML backend
4. Connect the ML backend to the annotation project
5. Open the annotation project again (doesn't matter with ML backend or not)
6. Open a task -> slow (5> seconds)

**Expected behavior**
For the task to open fast as it was before the ML backend was connected.

**Screenshots**
ML backend disabled: 
![image](https://user-images.githubusercontent.com/20222221/109754348-b2cda880-7b98-11eb-84f8-9a5e43247863.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version: 0.9.1.post1

**Additional context**
NA

**Comment by atakanokan** [comment]
Update: 
After deleting the ML backend connection (screenshot below), the task opening is now fast again. I am guessing when there is a ML backend added to the annotation project, label-studio tries to get predictions even if the ML backend is not connected. Would it be possible to bypass that so that the UI works much faster when a ML backend is added but not connected?



![image](https://user-images.githubusercontent.com/20222221/109766849-9850fa80-7bab-11eb-9f8c-df06b233e06d.png)

**Comment by Rishabh-hyperverge** [comment]
I am facing the exact same problem

**Comment by niklub** [comment]
Hey, guys, that issue has been fixed in https://github.com/heartexlabs/label-studio/pull/681/commits/33eb3e21e08a037d7d246bc87752a81b66470fc4 and will be released as 1.0.1 version

**Comment by Clemens-E** [comment]
@niklub I'm facing this issue, maybe the fix disappeared during refactoring?
During labeling, the POST "actions" call takes ~3300ms, even when loading of predictions is disabled:
![grafik](https://github.com/HumanSignal/label-studio/assets/43886026/0ab7c175-2039-49db-976b-f856caa62641)
![grafik](https://github.com/HumanSignal/label-studio/assets/43886026/2a4e6217-9e82-4cbe-b726-5e9da943e9a0)
Even tho label studio isnt even loading any predictions, it's just calling /health and /setup...
I tried playing with the env settings for timeouts without any luck.

When the ML backend is online, the POST "actions" call takes ~300ms.
Removing the configured ML backend resolves this, but is really annoying because my ML backend isnt online all the time.
I just create predictions for x images and later only label the ones with a low score.
