### ISSUE TITLE
Coco export start categories id from 0 instead of 1

### ISSUE THREAD

**Issue by Binnette** [heartexlabs/label-studio#6609]
Coco format needs that categories ids start with 1.

Ex: if I have 3 categories, their ids should be 1, 2 and 3.

But sadly label-studio via "export coco", set them as 0, 1 and 2.

**Comment by Binnette** [comment]
Ok I bypassed the issue by setting explicit categories id in "settings > labelling interface > code". Then add `category="1"`, etc.

Note, during previous export I didn't set this, so the export started with category id 0. But still this is a bug, it should start by 1 to be conform with Coco norms.

See example :
```xml
<View>

  <Header value="Select label and click the image to start"/>
  <Image name="image" value="$image" zoom="true" zoomControl="true"/>
  <PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
    <Label category="1" value="top" background="#f66151"/>
    <Label category="2" value="destination" background="#dc8add"/>
  </PolygonLabels>

</View>
```

**Comment by heidi-humansignal** [comment]
Hello,

Yes, if you set the category to what you want to start with. I'll create a bug ticket for it but please note that our team prioritizes bugs based on impact and how they align with our current roadmap, so we can't provide an exact timeline for a fix at this time. However, we’ll keep you updated as we make progress and will notify you once work begins and when the fix is delivered.
Thank you for your patience.


Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11746369884)

**Comment by Binnette** [comment]
Hi Abu, thank for your answer. No problem, I found a workaround, so this bug can be fixed when the team have needed resources. Have a nice day.
