### ISSUE TITLE
What is the purpose of 'mixpanel.com' usage

### ISSUE THREAD

**Issue by Freshwood** [heartexlabs/label-studio#674]
We are using the community Edition of Labelstudio.

We found out that the customer firewall was blocking many requests to mixpanel.com.

Why there are so many requests to mixpanel.com? 

For what are these request. Can we see which data is send to mixpanel.com?

We are using Labelstudio in many machine learning projects and we are using sensitive data. 
We have to clarify the origin of these requests to our customers.

Can you clarify this topic, please.

**Comment by deppp** [comment]
Hey @Freshwood, sure. We're basically collecting server API requests, those include the URLs being called, but not the data that's being imported / labeled or exported, we never collect any data that you work with(!). API calls are important to collect though, this is done so that we can understand what parts of the application are being used the most and helps us plan the product roadmap. You can disable that by setting the `collect_analytics=false` env variable.

**Comment by makseq** [comment]
Also it's mentioned about this in our docs: https://labelstud.io/guide/#Information-collected-by-Label-Studio
