### ISSUE TITLE
Polygon points not included in YOLOv8 OBB export when using Polygon tool

### ISSUE THREAD

**Issue by rejexx** [heartexlabs/label-studio#6750]
**Describe the bug**
Polygon's don't export in YOLOv8 OBB format when using `Polygon` tool only with `PolygonLabels`.  Perhaps the polygon tool isn't meant to be used this way, but I didn't see it listed in the docs.  It would be nice when using a combination of polygons and masks with only one label set if this feature still worked on YOLOv9 OBB export.

**To Reproduce**
Setup a new project with this labeling config:
```html
<View>
    <Header value="Select label and click the image to start" />
    <Image name="image" value="$image" zoom="true" />
    <Labels name="Type" toName="image" choice="single">
        <Label value="Airplane" background="red" />
        <Label value="Car" background="blue" />
    </Labels>
    <Polygon name="polygons" toName="image" />
</View>
```

Make annotations, and try exporting to YOLOv8 OBB.  The exported results do not contain the polygon points.

**Expected behavior**
the `Polygon` tool with labels behaves the same as PolygonLabels:
Using a config like this:
```html
<View>
    <Header value="Select label and click the image to start" />
    <Image name="image" value="$image" zoom="true" />
    <PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
        <Label value="Airplane" background="red" />
        <Label value="Car" background="blue" />
    </PolygonLabels>
</View>
```
When these polygons are exported in YOLO OBB, they contain all polygon points.  

**Environment (please complete the following information):**
 - OS: Windows 10, installed with pip.
 - Label Studio Version: 1.14.0

**Additional context**
Related: #3562

**Comment by heidi-humansignal** [comment]
Hello,

When using the `<Polygon>` tool in combination with `<Labels>`, the labels might not be correctly associated with the polygon annotations during export. This can lead to the exported YOLOv8 OBB files not containing the polygon points as you've experienced.
To ensure that your polygon annotations are correctly labeled and exported, we recommend using the `<PolygonLabels>` tag instead of `<Polygon>` with `<Labels>`. The `<PolygonLabels>` tag is specifically designed to create labeled polygons, and it maintains the association between the polygon regions and their labels during export.
Here's how you can update your labeling configuration:

```
<View>
    <Header value="Select label and click the image to start" />
    <Image name="image" value="$image" zoom="true" />
    <PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
        <Label value="Airplane" background="red" />
        <Label value="Car" background="blue" />
    </PolygonLabels>
</View>
```
By using `<PolygonLabels>`, each polygon you draw will be directly associated with its label, and this association will be preserved when exporting to YOLOv8 OBB format.
For more information on the `<PolygonLabels>` tag and its usage, please refer to our documentation:
PolygonLabels Tag Documentation
If you need to mix different tools or labels, ensure that they are properly connected in your labeling configuration. Using `PolygonLabels` should resolve the issue you're facing with the export not including polygon points.
Please let me know if this helps or if you have any further questions.


Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/12188787121)

**Comment by rejexx** [comment]
Thanks for the thorough response. I wondered if this was by design or not. Marking as closed.
