### ISSUE TITLE
Cannot find the right template file

### ISSUE THREAD

**Issue by Chaotic-chaos** [heartexlabs/label-studio#896]
Hi there, so sorry to interrupt. I am trying to translate the whole frontend of this project into Chinese. But I got stuck with this page. I cannot find the right page template or generation code for it so I can't translate it. Hope that u can give me some hints. Thanks sooooo much!
![Snipaste_2021-05-07_14-30-13](https://user-images.githubusercontent.com/32286124/117407306-f3eb8b80-af40-11eb-8d8b-afc21ff70347.png)

**Comment by makseq** [comment]
@Chaotic-chaos there are no templates since LS 1.0. it's a react app split into different parts. You need to modify them and rebuild.
https://github.com/heartexlabs/label-studio-frontend
https://github.com/heartexlabs/dm2
https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend/src

**Comment by Chaotic-chaos** [comment]
Thanks a lot again! And please keep this issue open for a while. I will close it as soon as I look into these repositories and have no other questions.
